Chr_1.trna1 (192731-192813)	Length: 83 bp
Type: Pro	Anticodon: TGG at 33-35 (192763-192765)	Score: 55.19
Possible intron: 37-47 (192767-192777)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGCCTTATGGTCTAGTAGTATGATTCCTCGTTTGGGttagctcaactTCGAGGAGGtCCTGGGTTCAACTCCCAGTGAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>..................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna2 (579068-579160)	Length: 93 bp
Type: Ser	Anticodon: CGA at 34-36 (579101-579103)	Score: 70.31
Possible intron: 38-48 (579105-579115)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACACCATAGCCAAGTGGTtACGGCGACAGATTCGAAtccgtttgactATCTGTTTCACTTTGTGAGCGCAGGTTCGAATCCTGCTGGTGTCG
Str: >>>>>>>..>>>..........<<<.>>>>>..................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_1.trna3 (607295-607387)	Length: 93 bp
Type: Ser	Anticodon: AGA at 34-36 (607328-607330)	Score: 66.94
Possible intron: 38-48 (607332-607342)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACATCATAGCCAAGTGGTtACGGCGACAGATTAGAAttcgttctaccATCTGTTTCACTTTGTGAGCGCAGGTTCGAATCCTGCTGGTGTCG
Str: >>>>>>>..>>>..........<<<.>>>>>..................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_1.trna4 (650671-650763)	Length: 93 bp
Type: Ser	Anticodon: AGA at 34-36 (650704-650706)	Score: 69.57
Possible intron: 38-48 (650708-650718)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACACCATAGCCAAGTGGTtACGGCGACAGATTAGAAttcgttctaccATCTGTTTCACTTTGTGAGCGCAGGTTCGAATCCTGCTGGTGTCG
Str: >>>>>>>..>>>..........<<<.>>>>>..................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_1.trna5 (1190571-1190643)	Length: 73 bp
Type: Thr	Anticodon: TGT at 34-36 (1190604-1190606)	Score: 57.91
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCATATAGCTCAGTGGTtAGAGCGTCCCTCATGTGTAGAGGAGGtCTCTGGTTCAATTCCGGATGTGGTCA
Str: >>>>>>>..>>>>........<<<<.>>.>>.......<<.<<.....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna6 (2854416-2854500)	Length: 85 bp
Type: Cys	Anticodon: GCA at 33-35 (2854448-2854450)	Score: 67.40
Possible intron: 37-49 (2854452-2854464)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GTCTCCATAGCTAAGTGGTATAGCGTGCGATTGCAActaaatgactgttATCGCGAGGtCCCGTGTTCGAACCACGGTGGGGACT
Str: >>>>>>>..>>>>.......<<<<.>>>>>....................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna7 (3158423-3158505)	Length: 83 bp
Type: Cys	Anticodon: GCA at 33-35 (3158455-3158457)	Score: 66.85
Possible intron: 37-47 (3158459-3158469)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GTCTCCATAGCTAAGTGGTATAGCGTGCGATTGCAAtggttgctattATCGCGAGGtCCCGTGTTCGAACCACGGTGGGGACT
Str: >>>>>>>..>>>>.......<<<<.>>>>>..................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna8 (3527572-3527659)	Length: 88 bp
Type: Glu	Anticodon: CTC at 34-36 (3527605-3527607)	Score: 50.61
Possible intron: 38-53 (3527609-3527624)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCGGATATGGTGTAACGGCtAACATTGCCGCCTCTCAtatttgagagagtttcCGCGGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna9 (3583829-3583900)	Length: 72 bp
Type: Glu	Anticodon: TTC at 34-36 (3583862-3583864)	Score: 59.98
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCCGATATGGTGTAACGGCtAACATTACCGCCTTTCACGCGGTAGCTCGGGGTTCGATTCCCCGTGTCGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna10 (3722261-3722344)	Length: 84 bp
Type: Asp	Anticodon: GTC at 34-36 (3722294-3722296)	Score: 50.61
Possible intron: 38-49 (3722298-3722309)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: TCTCCGTTAGTATATCGGTtAGTACACGCGCCTGTCAtgcaatagcgtgCGCGCGAAAGCTGGGTTCGACTCCCAGACGGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>...................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna11 (3718015-3717932)	Length: 84 bp
Type: Asp	Anticodon: GTC at 34-36 (3717982-3717980)	Score: 49.69
Possible intron: 38-49 (3717978-3717967)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: TCTCCGTTAGTATATCGGTtAGTACACGCGCCTGTCAtgccttagcgtgCGCGCGAAAGCTGGGTTCGACTCCCAGACGGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>...................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna12 (2914786-2914701)	Length: 86 bp
Type: Trp	Anticodon: CCA at 33-35 (2914754-2914752)	Score: 52.76
Possible intron: 37-50 (2914750-2914737)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GACTCCTTAGCTCAGTGGTAGAGCGTGAGATTCCAGcttgatctggagttTCCTCAAGGtCATCCGTTCAATCCGGGTAGGGGTCA
Str: >>>>>>>..>>>>.......<<<<.>>>>.......................<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna13 (1712856-1712764)	Length: 93 bp
Type: Ser	Anticodon: TGA at 34-36 (1712823-1712821)	Score: 69.39
Possible intron: 38-48 (1712819-1712809)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GCTGGGATGGCCGAGTGGTtAAGGCGAGTGATTTGAAtgcatctcaatATCACTTGGTGTTTCACCGCGTAGGTTCAAATCCTGCTTCCAGCG
Str: >>>>>>>..>>>..........<<<.>>>>>..................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_1.trna14 (941097-941025)	Length: 73 bp
Type: Met	Anticodon: CAT at 34-36 (941064-941062)	Score: 81.97
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GCCTCCTTGGCTCAGTCGGAAGAGCGTCAGTCTCATAATCTGAAGGtCGCAAGTTCGAACCTTGCAGGGGGCA
Str: >>>>>>>..>>>>........<<<<.>>>>.........<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna15 (804253-804181)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (804220-804218)	Score: 73.61
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TCCTTCTTAGCTCAGTTGGTAGAGCGCGTCACTAGTAATGACGAGGtCAGTCGTTCGAGTCGGCTAGAAGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_1.trna16 (662533-662449)	Length: 85 bp
Type: Lys	Anticodon: CTT at 35-37 (662499-662497)	Score: 64.05
Possible intron: 39-49 (662495-662485)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAaagactaggcgATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>..................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna1 (47764-47852)	Length: 89 bp
Type: Trp	Anticodon: CCA at 33-35 (47796-47798)	Score: 51.22
Possible intron: 37-53 (47800-47816)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GACTCCTTAGCTCAGTGGTAGAGCGTGAGATTCCAGcctttggttctggggttTCCTCAAGGtCATCCGTTCAATCCGGGTAGGGGTCA
Str: >>>>>>>..>>>>.......<<<<.>>>>..........................<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna2 (68524-68635)	Length: 112 bp
Type: Thr	Anticodon: TGT at 34-36 (68557-68559)	Score: 65.38
Possible intron: 38-76 (68561-68599)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCCTCCTTAGCTCAGTTGGTAGAGCGCATCACTTGTAgatcttccggaaacattagaaacttgcggacatctggatATGATGAGGtCAGTCGTTCGAGTCGGCTAGGGGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>..............................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna3 (170006-170078)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (170039-170041)	Score: 73.61
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TCCTTCTTAGCTCAGTTGGTAGAGCGCGTCACTAGTAATGACGAGGtCAGTCGTTCGAGTCGGCTAGAAGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna4 (1134552-1134634)	Length: 83 bp
Type: Phe	Anticodon: GAA at 34-36 (1134585-1134587)	Score: 59.91
Possible intron: 38-47 (1134589-1134598)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGGGGCATAGCTCAGTTGGGAGAGCAGTAGACTGAAGcacatgcgtaTTCTAAAGGtCCCGCGTTCAATCCGCGGTGCCCCCA
Str: >>>>>>>..>>>>........<<<<..>>>>.................<<<<......>>>>>.......<<<<<<<<<<<<.

Chr_2.trna5 (1304774-1304846)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (1304807-1304809)	Score: 60.68
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCGGATAGCTCAGTGGTtAGAGCATCCACCTAGTGTTGGGACGGtCCTCGGTTCAATCCCGGGTCTGGTCG
Str: >>>>>>>..>>>>........<<<<.>>>...........<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna6 (1513840-1513926)	Length: 87 bp
Type: Ile	Anticodon: TAT at 34-36 (1513873-1513875)	Score: 66.02
Possible intron: 38-51 (1513877-1513890)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GCCCGTGTAGCTTAACTGGTAGAGCGTTGTACTTATGaggttacgtaggctATGCAAAGGtCCCGAGTTCGACCCTCGGCATGGGCA
Str: >>>>>>>..>>>>........<<<<.>>>>>.....................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna7 (2167897-2167969)	Length: 73 bp
Type: Thr	Anticodon: TGT at 34-36 (2167930-2167932)	Score: 50.71
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: CACCATATAGCTCAGTGGTtAGAGCGTCCCTCATGTGTAGAGGAGGtCTCTGGTTCAAATCCGGATGTGGTCA
Str: .>>>>>>..>>>>........<<<<.>>.>>.......<<.<<.....>>>>>.......<<<<<<<<<<<..

Chr_2.trna8 (2598273-2598368)	Length: 96 bp
Type: Asn	Anticodon: GTT at 35-37 (2598307-2598309)	Score: 75.03
Possible intron: 39-60 (2598311-2598332)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: TGCCCCATGGCTGAGTTGGTtACAGCGTCCGACTGTTAcgaacactaagtgctctagacaATCGGAAGGtCGTGAGTTCGAGCCTCACTGGGGCAG
Str: >>>>>>>..>>>>.........<<<<.>>>>>.............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna9 (2840783-2840887)	Length: 105 bp
Type: Met	Anticodon: CAT at 35-37 (2840817-2840819)	Score: 68.00
Possible intron: 39-69 (2840821-2840851)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GCCTTCTTGGCTCAGTTGGCtAGAGCGCAGGTCTCATAcgcaagtgtatgagtgggtctaacccacgaaATCCTGAGGtCGCAAGTTCGAGCCTTGCAGGGGGCA
Str: >>>>>>>..>>>>.........<<<<.>>>>........................................<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna10 (3426650-3426751)	Length: 102 bp
Type: Ser	Anticodon: GCT at 34-36 (3426683-3426685)	Score: 59.70
Possible intron: 38-57 (3426687-3426706)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GTCACTTTGCCGGAGTGGTtAACGGGATCGCCTGCTAttggccttcgggccaggcaaAGCGGTTGGTCTTTGACCGCGAGTGTTCGAATCGCTCAGGTGACG
Str: >>>>>>>..>>>..........<<<.>>>>>...........................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_2.trna11 (3602571-3602759)	Length: 189 bp
Type: Glu	Anticodon: CTC at 34-36 (3602604-3602606)	Score: 29.61
Possible intron: 38-154 (3602608-3602724)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: TTGGATATGGTGTAACGGCtAACACGACCGCCTCTCGtacttactctgtatacataaagggtttttttctgtgtatcagagagagtagtatgagcatgcactactcagtgtagttcaaggatactcattttatagcctgagggcttgagcttgaGGCGGAAGCTCGGGGTTCGACTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<..>>>>............................................................................................................................<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna12 (3608907-3608994)	Length: 88 bp
Type: Glu	Anticodon: CTC at 34-36 (3608940-3608942)	Score: 48.20
Possible intron: 38-53 (3608944-3608959)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCGGATATGGTGTAACGGCtAACATTGCCGCCTCTCAtgatcgggagtcagtcCGCGGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna13 (3611612-3611698)	Length: 87 bp
Type: Glu	Anticodon: CTC at 34-36 (3611645-3611647)	Score: 25.13
Possible intron: 38-55 (3611649-3611666)
Possible pseudogene:  HMM Sc=2.31	Sec struct Sc=22.82
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: TCGGATATGGTGTAACGGCtAACATTGCCGCCTCTCAtctttcgagagtcaggtcCGCGGCAGCTCGGGGTTCGACCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.........................<<<<<....>.>>>.....<<<<<<<<<<<.

Chr_2.trna14 (3642436-3642533)	Length: 98 bp
Type: Glu	Anticodon: CTC at 34-36 (3642469-3642471)	Score: 38.82
Possible intron: 38-63 (3642473-3642498)
Possible pseudogene:  HMM Sc=9.59	Sec struct Sc=29.23
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCGGATAGGGTGTAACGGCtAACATTGCTGCCTCTCAtcccaacctttctcgagagtttggtcCGCAGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.................................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna15 (3646054-3646143)	Length: 90 bp
Type: Glu	Anticodon: CTC at 34-36 (3646087-3646089)	Score: 48.11
Possible intron: 38-55 (3646091-3646108)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: TCGGATATGGTGTAACGGCtAACATTGCTGCCTCTCAtcttgcgagagtttggtcCGCAGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna16 (3667703-3667813)	Length: 111 bp
Type: Leu	Anticodon: CAA at 35-37 (3667737-3667739)	Score: 55.16
Possible intron: 39-65 (3667741-3667767)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GGCAAGATGGCCGAGCGGTctATGGCGTGTGACTCAAGcgaaagcttgcctctgtcattaggggtTTCTCATGGGAGTATTCCCGCGTGGGTTCAAATCCCACTCTTGTCA
Str: >>>>>>>..>>>>.........<<<<.>>.>>..................................<<.<<..>>.>...<.<<..>>>>>.......<<<<<<<<<<<<.

Chr_2.trna17 (3675659-3675754)	Length: 96 bp
Type: Glu	Anticodon: CTC at 34-36 (3675692-3675694)	Score: 49.81
Possible intron: 38-61 (3675696-3675719)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: TCGGATATGGTGTAACGGCtAACATTGCTGCCTCTCAttatctgtcattacaaagtgtgtcCGCAGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>...............................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna18 (3720690-3720762)	Length: 73 bp
Type: Arg	Anticodon: TCT at 34-36 (3720723-3720725)	Score: 72.02
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GCCCTCGTTGTCTAATGGTtATGACGTCAGACTTCTAATCTGGAGGtTGCGAGTTCGAGTCTCGCCGGGGGTA
Str: >>>>>>>..>>>..........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna19 (3737632-3737720)	Length: 89 bp
Type: Glu	Anticodon: CTC at 34-36 (3737665-3737667)	Score: 49.26
Possible intron: 38-54 (3737669-3737685)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: TCGGATATGGTGTAACGGCtAACATTGCTGCCTCTCAttcagtagagtttggtcCGCAGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna20 (3718900-3718811)	Length: 90 bp
Type: Glu	Anticodon: CTC at 34-36 (3718867-3718865)	Score: 49.91
Possible intron: 38-55 (3718863-3718846)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: TCGGATATGGTGTAGCGGCtAACATTGCTGCCTCTCAtctcatcgggagtctgtcCGCAGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna21 (3713953-3713841)	Length: 113 bp
Type: Leu	Anticodon: CAA at 35-37 (3713919-3713917)	Score: 54.78
Possible intron: 39-67 (3713915-3713887)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGCAAGATGGCCGAGCGGTctATGGCGTGTGACTCAAGcgtaacagcttgcctctgtcattaggggtTTCTCATGGGAGTATTCCCGCGTGGGTTCAAATCCCACTCTTGTCA
Str: >>>>>>>..>>>>.........<<<<.>>.>>....................................<<.<<..>>.>...<.<<..>>>>>.......<<<<<<<<<<<<.

Chr_2.trna22 (3598595-3598508)	Length: 88 bp
Type: Glu	Anticodon: CTC at 34-36 (3598562-3598560)	Score: 48.56
Possible intron: 38-53 (3598558-3598543)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCGGATATGGTGTAACGGCtAACATTGCCGCCTCTCAtcgtcgagagtttgtcCGCGGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna23 (3542546-3542445)	Length: 102 bp
Type: Ser	Anticodon: GCT at 34-36 (3542513-3542511)	Score: 61.70
Possible intron: 38-57 (3542509-3542490)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GTCACTTTGCCGGAGTGGTtAACGGGATCGCCTGCTAttggccttcgggtcaggcaaAGCGGTTGGTCTTTGACCGCGTGTGTTCGAATCGCACAGGTGACG
Str: >>>>>>>..>>>..........<<<.>>>>>...........................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_2.trna24 (2914517-2914437)	Length: 81 bp
Type: Trp	Anticodon: CCA at 33-35 (2914485-2914483)	Score: 53.40
Possible intron: 37-45 (2914481-2914473)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GACTCCTTAGCTCAGTGGTAGAGCGTGAGATTCCAGcttgggaaaTCCTCAAGGtCATCCGTTCAATCCGGGTAGGGGTCA
Str: >>>>>>>..>>>>.......<<<<.>>>>..................<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna25 (2861328-2861226)	Length: 103 bp
Type: Met	Anticodon: CAT at 35-37 (2861294-2861292)	Score: 68.24
Possible intron: 39-67 (2861290-2861262)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GCCTTCTTGGCTCAGTTGGCtAGAGCGCAGGTCTCATAcgcaagtatgagtgggttcaacccacgaaATCCTGAGGtCGCAAGTTCGAGCCTTGCAGGGGGCA
Str: >>>>>>>..>>>>.........<<<<.>>>>......................................<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna26 (2712873-2712792)	Length: 82 bp
Type: Ser	Anticodon: AGA at 34-36 (2712840-2712838)	Score: 77.78
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GGCGCTATAGCCAAGTGGTtACGGCGACAGATTAGAAATCTGTTCCTCTTTGAGGGCGCAGGTTCGAATCCTGCTGGCGTCG
Str: >>>>>>>..>>>..........<<<.>>>>>.......<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_2.trna27 (2600010-2599920)	Length: 91 bp
Type: Asn	Anticodon: GTT at 35-37 (2599976-2599974)	Score: 73.19
Possible intron: 39-55 (2599972-2599956)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: TGCCCCATGGCTGAGTTGGTtACAGCGTCCGACTGTTAgcgccttgtgccaagcaATCGGAAGGtCGTGAGTTCGAGCCTCACTGGGGCAG
Str: >>>>>>>..>>>>.........<<<<.>>>>>........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna28 (2276828-2276733)	Length: 96 bp
Type: Leu	Anticodon: TAA at 36-38 (2276793-2276791)	Score: 57.17
Possible intron: 40-49 (2276789-2276780)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGTAGCGTGGCCGAGTTGGTctAAGGCGTTGGATTTAAGttcttcttgaTTCCCAATGGGCGAAAGTCCGCGCGAGTTCGAACCTCGCCGCTACCA
Str: >>>>>>>..>>>............<<<.>.>>>.................<<<.<..>>>>....<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_2.trna29 (1024923-1024834)	Length: 90 bp
Type: Phe	Anticodon: GAA at 34-36 (1024890-1024888)	Score: 59.45
Possible intron: 38-54 (1024886-1024870)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GGGGGCATAGCTCAGTTGGGAGAGCAGTAGACTGAAGcacgaagcacttgtgtaTTCTAAAGGtCCCGCGTTCAATCCGCGGTGCCCCCA
Str: >>>>>>>..>>>>........<<<<..>>>>........................<<<<......>>>>>.......<<<<<<<<<<<<.

Chr_2.trna30 (1024610-1024520)	Length: 91 bp
Type: Phe	Anticodon: GAA at 34-36 (1024577-1024575)	Score: 60.36
Possible intron: 38-55 (1024573-1024556)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GGGGGCATAGCTCAGTTGGGAGAGCAGTAGACTGAAGcaattcgcaagagttgtaTTCTAAAGGtCCCGCGTTCAATCCGCGGTGCCCCCA
Str: >>>>>>>..>>>>........<<<<..>>>>.........................<<<<......>>>>>.......<<<<<<<<<<<<.

Chr_2.trna31 (358307-358206)	Length: 102 bp
Type: Ser	Anticodon: GCT at 34-36 (358274-358272)	Score: 59.70
Possible intron: 38-57 (358270-358251)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GTCACTTTGCCGGAGTGGTtAACGGGATCGCCTGCTAttggccttcgggccaggcaaAGCGGTTGGTCTTTGACCGCGAGTGTTCGAATCGCTCAGGTGACG
Str: >>>>>>>..>>>..........<<<.>>>>>...........................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_2.trna32 (215299-215189)	Length: 111 bp
Type: Ser	Anticodon: CGA at 34-36 (215266-215264)	Score: 68.08
Possible intron: 38-66 (215262-215234)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GGCGCTATAGCCAAGTGGTtACGGCGACAGATTCGAAtgacatcctcttccgaggataagcttgctATCTGTTCCTCTTTGAGGGCGCAGGTTCGAATCCTGCTGGCGTCG
Str: >>>>>>>..>>>..........<<<.>>>>>....................................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_2.trna33 (159600-159528)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (159567-159565)	Score: 73.61
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TCCTTCTTAGCTCAGTTGGTAGAGCGCGTCACTAGTAATGACGAGGtCAGTCGTTCGAGTCGGCTAGAAGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_2.trna34 (124303-124226)	Length: 78 bp
Type: Thr	Anticodon: CGT at 38-40 (124266-124264)	Score: 26.10
Possible pseudogene:  HMM Sc=9.88	Sec struct Sc=16.22
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCCTTTttaaGTAGCTCAGTTGGTAGCGCGTGTCACTCGTAaATGACGAGGtCAGTTGTTTGAGTCGGCACGAAGGAA
Str: >>>>>>....>..>>.>........<.<<.>>>>>........<<<<<......>>>>.......<<<<.<<<<<<<.

Chr_3.trna1 (532852-532935)	Length: 84 bp
Type: Phe	Anticodon: GAA at 34-36 (532885-532887)	Score: 59.40
Possible intron: 38-48 (532889-532899)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGGGCATAGCTCAGTTGGGAGAGCAGTAGACTGAAGcttcgagcgtaTTCTAAAGGtCCCGCGTTCAATCCGCGGTGCCCCCA
Str: >>>>>>>..>>>>........<<<<..>>>>..................<<<<......>>>>>.......<<<<<<<<<<<<.

Chr_3.trna2 (1704554-1704647)	Length: 94 bp
Type: Leu	Anticodon: TAG at 35-37 (1704588-1704590)	Score: 59.51
Possible intron: 39-52 (1704592-1704605)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCAACATGGCCGAGTGGTctAAGGCGCTGGAATTAGGtcatgcgatcgaaaATCCAGTCTTCACGGGCGAGGGTTCGAATCCCTCTGTTGTCA
Str: >>>>>>>..>>>...........<<<.>>>>>.....................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_3.trna3 (1831007-1831079)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (1831040-1831042)	Score: 73.61
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TCCTTCTTAGCTCAGTTGGTAGAGCGCGTCACTAGTAATGACGAGGtCAGTCGTTCGAGTCGGCTAGAAGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna4 (2268450-2268535)	Length: 86 bp
Type: Gln	Anticodon: CTG at 34-36 (2268483-2268485)	Score: 66.54
Possible intron: 38-51 (2268487-2268500)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCGCTATAGTGTAGTGGTtATCACTCGGGATTCTGAtgtctacgtttgatTTCCCGAAACCCAGGTTCGAACCCTGGTAGCGCCT
Str: >>>>>>>..>>>..........<<<.>>>>>.....................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna5 (3113976-3114060)	Length: 85 bp
Type: Pro	Anticodon: TGG at 33-35 (3114008-3114010)	Score: 54.45
Possible intron: 37-49 (3114012-3114024)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGCCTTATGGTCTAGTAGTATGATTCCTCGTTTGGGtttcggtccgaaaTCGAGGAGGtCCTGGGTTCAACTCCCAGTGAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>....................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna6 (3152520-3152602)	Length: 83 bp
Type: Pro	Anticodon: AGG at 33-35 (3152552-3152554)	Score: 57.70
Possible intron: 37-47 (3152556-3152566)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGCCTGATGGTCTAGTAGTATGATTCCTTGTTAGGGttcgccttataTCGAGGAGGtCCCGGGTTCAATTCCCGGTCAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>..................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna7 (3174596-3174667)	Length: 72 bp
Type: Asp	Anticodon: GTC at 34-36 (3174629-3174631)	Score: 58.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCTCCGTTAGTATATCGGTtAGTACACGCGCCTGTCACGCGCGAAAGCTGGGTTCGACTCCCAGACGGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna8 (3576954-3577026)	Length: 73 bp
Type: Met	Anticodon: CAT at 34-36 (3576987-3576989)	Score: 67.99
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: AGCAACATAGCTCAGGTGGTAGAGCGCGGGGCTCATAACCCCGAGGtCACTCGATCGAGACGAGTTGTTGCTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna9 (3534312-3534240)	Length: 73 bp
Type: Phe	Anticodon: GAA at 34-36 (3534279-3534277)	Score: 65.67
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGGAGCATAGCTCAGTTGGGAGAGCAGTAGACTGAAGTTCTAAAGGtCCCGCGTTCGATCCGCGGTGGTCCCA
Str: >>>>.>>..>>>>........<<<<..>>>>.......<<<<......>>>>>.......<<<<<<<.<<<<.

Chr_3.trna10 (3080892-3080811)	Length: 82 bp
Type: Asp	Anticodon: GTC at 34-36 (3080859-3080857)	Score: 51.85
Possible intron: 38-47 (3080855-3080846)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCTCCGTTAGTATATCGGTtAGTACACGCGCCTGTCAtttaattggcCGCGCGAAAGCTGGGTTCGACTCCCAGACGGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>.................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna11 (3057092-3057004)	Length: 89 bp
Type: Thr	Anticodon: AGT at 34-36 (3057059-3057057)	Score: 63.35
Possible intron: 38-53 (3057055-3057040)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: TCCTTCTTAGCTCAGTTGGTAGAGCGCGTCACTAGTAcgtccatccgcggattATGACGAGGtCAGTCGTTCGAGTCGGCTAGAAGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna12 (2905855-2905772)	Length: 84 bp
Type: His	Anticodon: GTG at 34-36 (2905822-2905820)	Score: 49.17
Possible intron: 38-49 (2905818-2905807)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GTCCGTATCGATTAGGGGTtAAATCACTTCGTTGTGGttgagcatcgctCCGAAGAGCCGCTGGTTCGATTCCAGCTACGGACA
Str: >>>>>>>..>>>>........<<<<.>>>>>...................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna13 (2890418-2890327)	Length: 92 bp
Type: His	Anticodon: GTG at 34-36 (2890385-2890383)	Score: 48.36
Possible intron: 38-57 (2890381-2890362)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GTCCGTATCGATTAGGGGTtAAATCACTTCGTTGTGGcatgcactgagcgtacaactCCGAAGAGCCGCTGGTTCGATTCCAGCTACGGACA
Str: >>>>>>>..>>>>........<<<<.>>>>>...........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna14 (2663662-2663589)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (2663628-2663626)	Score: 79.94
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGCGTAGTTGGTtATCGCATCTGTCTAACACACAGAAGGtCGCCAGTTCGAACCTGGCTCGAATCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna15 (2252876-2252791)	Length: 86 bp
Type: Gln	Anticodon: CTG at 34-36 (2252843-2252841)	Score: 65.91
Possible intron: 38-51 (2252839-2252826)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCGCTATAGTGTAGTGGTtATCACTCGGGATTCTGAtctaatcgtccgatTTCCCGAAACCCAGGTTCGAACCCTGGTAGCGCCT
Str: >>>>>>>..>>>..........<<<.>>>>>.....................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna16 (2252703-2252624)	Length: 80 bp
Type: Gln	Anticodon: CTG at 34-36 (2252670-2252668)	Score: 67.42
Possible intron: 38-45 (2252666-2252659)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GGCGCTATAGTGTAGTGGTtATCACTCGGGATTCTGAttcacaatTTCCCGAAACCCAGGTTCGAACCCTGGTAGCGCCT
Str: >>>>>>>..>>>..........<<<.>>>>>...............<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna17 (1831490-1831396)	Length: 95 bp
Type: Gln	Anticodon: TTG at 34-36 (1831457-1831455)	Score: 63.71
Possible intron: 38-60 (1831453-1831431)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGCGCTATAGTGTAGTGGTtATCACTCGGGATTTTGAagaggcgcgtctgcctttaaatcTTCCCGAAACCCAGGTTCGAACCCTGGTAGCGCCT
Str: >>>>>>>..>>>..........<<<.>>>>>..............................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna18 (665836-665763)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (665802-665800)	Score: 76.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCTTGGGTTCGATCCCCACGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<......>>>>.......<<<<.<<<<<<<.

Chr_3.trna19 (140950-140845)	Length: 106 bp
Type: Pro	Anticodon: AGG at 33-35 (140918-140916)	Score: 52.68
Possible intron: 37-70 (140914-140881)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCCTGATGGTCTAGTAGTATGATTCCTTGTTAGGGagcagcaggcgctaaccgcgtaggcttgcgaattTCGAGGAGGtCCCGGGTTCAATTCCCGGTCAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>.........................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna20 (89529-89457)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (89496-89494)	Score: 60.68
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCGGATAGCTCAGTGGTtAGAGCATCCACCTAGTGTTGGGACGGtCCTCGGTTCAATCCCGGGTCTGGTCG
Str: >>>>>>>..>>>>........<<<<.>>>...........<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna21 (79230-79141)	Length: 90 bp
Type: Pro	Anticodon: AGG at 33-35 (79198-79196)	Score: 55.47
Possible intron: 37-54 (79194-79177)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GGCCTGATGGTCTAGTAGTATGATTCCTTGTTAGGGagcgttccgcgctaagttTCGAGGAGGtCCCGGGTTCAATTCCCGGTCAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>.........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_3.trna22 (60761-60654)	Length: 108 bp
Type: Pro	Anticodon: AGG at 33-35 (60729-60727)	Score: 54.28
Possible intron: 37-72 (60725-60690)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: GGCCTGATGGTCTAGTAGTATGATTCCTTGTTAGGGagctttcggcgcttattcggcgttgatttgcgaattTCGAGGAGGtCCCGGGTTCAATTCCCGGTCAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>...........................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna1 (65521-65608)	Length: 88 bp
Type: Glu	Anticodon: CTC at 34-36 (65554-65556)	Score: 48.70
Possible intron: 38-53 (65558-65573)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCGGATATGGTGTAACGGCtAACATTGCCGCCTCTCAtcgttgagagctagtcCGCGGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna2 (79941-80012)	Length: 72 bp
Type: Glu	Anticodon: TTC at 34-36 (79974-79976)	Score: 59.98
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCCGATATGGTGTAACGGCtAACATTACCGCCTTTCACGCGGTAGCTCGGGGTTCGATTCCCCGTGTCGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna3 (85254-85359)	Length: 106 bp
Type: Leu	Anticodon: AAG at 35-37 (85288-85290)	Score: 64.16
Possible intron: 39-64 (85292-85317)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCGAGATGGCCGAGCGGTctAAGGCGCCAGACTAAGGagaccagcatgttcagacatgcagttATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTCTCGTCA
Str: >>>>>>>..>>>...........<<<.>>>>>.................................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_4.trna4 (98192-98280)	Length: 89 bp
Type: Glu	Anticodon: CTC at 34-36 (98225-98227)	Score: 48.48
Possible intron: 38-54 (98229-98245)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: TCGGATATGGTGTAACGGCtAACATTGCCGCCTCTCAtcgaacgagagtcagtcCGCGGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna5 (103233-103338)	Length: 106 bp
Type: Leu	Anticodon: AAG at 35-37 (103267-103269)	Score: 63.03
Possible intron: 39-64 (103271-103296)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCGAGATGGCCGAGCGGTctAAGGCGCCAGACTAAGGagaccagcacgtacagacgtgcagttATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTCTCGTCA
Str: >>>>>>>..>>>...........<<<.>>>>>.................................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_4.trna6 (196386-196457)	Length: 72 bp
Type: Glu	Anticodon: TTC at 34-36 (196419-196421)	Score: 59.98
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCCGATATGGTGTAACGGCtAACATTACCGCCTTTCACGCGGTAGCTCGGGGTTCGATTCCCCGTGTCGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna7 (475758-475843)	Length: 86 bp
Type: Asp	Anticodon: GTC at 34-36 (475791-475793)	Score: 51.66
Possible intron: 38-51 (475795-475808)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: TCTCCGTTAGTATATCGGTtAGTACACGCGCCTGTCAttgcacaagcaataCGCGCGAAAGCTGGGTTCGACTCCCAGACGGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>.....................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna8 (671911-672033)	Length: 123 bp
Type: Lys	Anticodon: CTT at 35-37 (671945-671947)	Score: 61.23
Possible intron: 39-87 (671949-671997)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAcaaaccgtctaggatagggtacagaccttccttgtttggatatacggaaATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>........................................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna9 (786691-786800)	Length: 110 bp
Type: Lys	Anticodon: CTT at 35-37 (786725-786727)	Score: 60.84
Possible intron: 39-74 (786729-786764)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAtggtctgggacgggttgctgttcctatcattaggatATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>...........................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna10 (787605-787693)	Length: 89 bp
Type: Lys	Anticodon: CTT at 35-37 (787639-787641)	Score: 62.01
Possible intron: 39-53 (787643-787657)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAtcgtctaggacgggcATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>......................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna11 (1772288-1772360)	Length: 73 bp
Type: Phe	Anticodon: GAA at 34-36 (1772321-1772323)	Score: 65.67
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGGAGCATAGCTCAGTTGGGAGAGCAGTAGACTGAAGTTCTAAAGGtCCCGCGTTCGATCCGCGGTGGTCCCA
Str: >>>>.>>..>>>>........<<<<..>>>>.......<<<<......>>>>>.......<<<<<<<.<<<<.

Chr_4.trna12 (1954874-1954944)	Length: 71 bp
Type: Gly	Anticodon: CCC at 33-35 (1954906-1954908)	Score: 57.12
         *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GCATTGATGGTGTAGCGGTAACATTGGGTCTTCCCATGGCCTAGCTCCGGGTTCGACTCCCGGTCAATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna13 (2507836-2507922)	Length: 87 bp
Type: Arg	Anticodon: CCG at 34-36 (2507869-2507871)	Score: 58.32
Possible intron: 38-51 (2507873-2507886)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GGCGGGCTAGCGTAATGGTtAACGCGCCAGTTTCCGGtggacttcccacttAGCTGGAGAtTCTGGGTTCGAGTCCCAGGTTCGTCG
Str: >>>>>>>..>>>>........<<<<.>>>>>.....................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna14 (2564103-2564173)	Length: 71 bp
Type: Gly	Anticodon: CCC at 33-35 (2564135-2564137)	Score: 57.12
         *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GCATTGATGGTGTAGCGGTAACATTGGGTCTTCCCATGGCCTAGCTCCGGGTTCGACTCCCGGTCAATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna15 (2647907-2648004)	Length: 98 bp
Type: Lys	Anticodon: TTT at 35-37 (2647941-2647943)	Score: 62.73
Possible intron: 39-62 (2647945-2647968)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTTTTAgggcccggtcagtttgaccaatccATCTGAAGGcTGCGAGTTCGATCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>...............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna16 (2976777-2976862)	Length: 86 bp
Type: Lys	Anticodon: CTT at 35-37 (2976811-2976813)	Score: 63.54
Possible intron: 39-50 (2976815-2976826)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAcgtaagcaaggcATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>...................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna17 (3161629-3161533)	Length: 97 bp
Type: Gly	Anticodon: GCC at 33-35 (3161597-3161595)	Score: 49.53
Possible intron: 37-62 (3161593-3161568)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GCATCAATGGGGTAGTGGTAACCTGGATCGTTGCCAttgataaggctacgtgctagcttgacTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.................................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna18 (3044539-3044454)	Length: 86 bp
Type: Gly	Anticodon: GCC at 33-35 (3044507-3044505)	Score: 48.42
Possible intron: 37-51 (3044503-3044489)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GCATCAATGGGGTAGTGGTAACCTGGATCGTTGCCActcgcgtcgactagcTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna19 (3034954-3034866)	Length: 89 bp
Type: Gly	Anticodon: GCC at 33-35 (3034922-3034920)	Score: 48.95
Possible intron: 37-54 (3034918-3034901)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GCATCAATGGGGTAGTGGTAACCTGGATCGTTGCCActcttatcggcgcctaagTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna20 (2941425-2941332)	Length: 94 bp
Type: Arg	Anticodon: TCG at 33-35 (2941393-2941391)	Score: 68.00
Possible intron: 37-58 (2941389-2941368)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCTACCTGGCGCAATGGTAGCGCGTTTGGCTTCGAtggctttacggctccaatggacACCAAAAGGtTACAGGTTCGATCCCTGTGGTGGTCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna21 (2769566-2769471)	Length: 96 bp
Type: Lys	Anticodon: TTT at 35-37 (2769532-2769530)	Score: 61.84
Possible intron: 39-60 (2769528-2769507)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTTTTAgggccggccgtacgaccaatccATCTGAAGGcTGCGAGTTCGATCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>.............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna22 (1957247-1957148)	Length: 100 bp
Type: Pro	Anticodon: CGG at 33-35 (1957215-1957213)	Score: 56.90
Possible intron: 37-64 (1957211-1957184)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GGCCCAATGGTCTAGTAGTATGATACTCGCTTCGGGagttttcccgcgtattcgttacgtagatTGTGAGTGGtCCCGGGTTCAATTCCCGGTTGGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>...................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna23 (1389271-1389175)	Length: 97 bp
Type: Thr	Anticodon: TGT at 33-35 (1389239-1389237)	Score: 67.23
Possible intron: 37-61 (1389235-1389211)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GCCGCGTTGGCGTAGTGGTAGCGCGTCCCACTTGTAacagcttgtgatagcaagcaagttcATGGGAAGGtCACTCGTTCAATCCGGGTACGTGGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna24 (735971-735862)	Length: 110 bp
Type: Lys	Anticodon: CTT at 35-37 (735937-735935)	Score: 60.84
Possible intron: 39-74 (735933-735898)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAtggtctgggacgggttgctgttcctatcattaggatATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>...........................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna25 (735169-735059)	Length: 111 bp
Type: Lys	Anticodon: CTT at 35-37 (735135-735133)	Score: 61.75
Possible intron: 39-75 (735131-735095)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAtcgtctaggacgggttaatttccttccataggatggaATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>............................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna26 (679303-679197)	Length: 107 bp
Type: Lys	Anticodon: CTT at 35-37 (679269-679267)	Score: 60.04
Possible intron: 39-71 (679265-679233)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAccgtctaggatcgggtagttccttccgtttggaATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>........................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna27 (669642-669522)	Length: 121 bp
Type: Lys	Anticodon: CTT at 35-37 (669608-669606)	Score: 61.74
Possible intron: 39-85 (669604-669558)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAaccgtcgactaggagagggtaaataccttccttgtttggataaggaaATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>......................................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna28 (656844-656723)	Length: 122 bp
Type: Lys	Anticodon: CTT at 35-37 (656810-656808)	Score: 60.68
Possible intron: 39-86 (656806-656759)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTCTTAcaaaccgtctaggatagggtaccgaccttccttgtttggatattcgaaATCTGAAGGcTGCGAGTTCGACCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......................................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna29 (142666-142579)	Length: 88 bp
Type: Glu	Anticodon: CTC at 34-36 (142633-142631)	Score: 49.34
Possible intron: 38-53 (142629-142614)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCGGATATGGTGTAACGGCtAACATTGCCGCCTCTCAtatcagagagtttgccCGCGGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_4.trna30 (97826-97721)	Length: 106 bp
Type: Leu	Anticodon: AAG at 35-37 (97792-97790)	Score: 63.03
Possible intron: 39-64 (97788-97763)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCGAGATGGCCGAGCGGTctAAGGCGCCAGACTAAGGagaccagcacgtacagacgtgcagttATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTCTCGTCA
Str: >>>>>>>..>>>...........<<<.>>>>>.................................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_4.trna31 (97330-97225)	Length: 106 bp
Type: Leu	Anticodon: AAG at 35-37 (97296-97294)	Score: 64.16
Possible intron: 39-64 (97292-97267)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCGAGATGGCCGAGCGGTctAAGGCGCCAGACTAAGGagaccagcatgttcagacatgcagttATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTCTCGTCA
Str: >>>>>>>..>>>...........<<<.>>>>>.................................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_5.trna1 (6689-6778)	Length: 90 bp
Type: Arg	Anticodon: TCT at 36-38 (6724-6726)	Score: 23.82
Possible intron: 40-47 (6728-6735)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: TCGGGTATAGCATAAAGGTAGTGCAgcaCAACGCTTCTActctgagtACGAACGGGGGTGCGCGTCGGGGTTCGATTCCCCGTACTCGAT
Str: >>>>>>>..>>>>.......<<<<.......>>...............<<.....>.>><<.<..>>>>>.......<<<<<<<<<<<<.

Chr_5.trna2 (222981-223066)	Length: 86 bp
Type: Gly	Anticodon: GCC at 33-35 (223013-223015)	Score: 49.70
Possible intron: 37-51 (223017-223031)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GCATCAATGGGGTAGTGGTAACCTGGATCGTTGCCActctacgagcttgacTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna3 (749819-749911)	Length: 93 bp
Type: Asn	Anticodon: GTT at 35-37 (749853-749855)	Score: 74.21
Possible intron: 39-57 (749857-749875)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TGCCCCATGGCTGAGTTGGTtACAGCGTCCGACTGTTAgcgactttggttgcagactATCGGAAGGtCGTGAGTTCGAGCCTCACTGGGGCAG
Str: >>>>>>>..>>>>.........<<<<.>>>>>..........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna4 (867352-867424)	Length: 73 bp
Type: Thr	Anticodon: TGT at 34-36 (867385-867387)	Score: 47.72
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCATATAGCTCAGTGGTtAGTGTGTTGCTCATGTGTAGAGGAGGtCTCTGGTTCAAATCCGGATGTGGTCA
Str: >>>>>>>..>>.>........<.<<.>>.>>.......<<.<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna5 (889072-889144)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (889105-889107)	Score: 41.15
Possible pseudogene:  HMM Sc=36.22	Sec struct Sc=4.93
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCGGATAGCTCAGTAGTtAGAGCATCCACCTAGTGTTGGGTCGGtCCTCGGTTCAATCCTGGGTCTGGTCG
Str: >>>>>>>..>>>>........<<<<..>>...........<<......>>>>>.......<<<<<<<<<<<<.

Chr_5.trna6 (1113880-1113970)	Length: 91 bp
Type: Lys	Anticodon: TTT at 35-37 (1113914-1113916)	Score: 64.10
Possible intron: 39-55 (1113918-1113934)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTTTTAgggccagtcatgtgaccATCTGAAGGcTGCGAGTTCGATCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna7 (2419730-2419802)	Length: 73 bp
Type: Arg	Anticodon: TCT at 34-36 (2419763-2419765)	Score: 72.02
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GCCCTCGTTGTCTAATGGTtATGACGTCAGACTTCTAATCTGGAGGtTGCGAGTTCGAGTCTCGCCGGGGGTA
Str: >>>>>>>..>>>..........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna8 (2722468-2722546)	Length: 79 bp
Type: Arg	Anticodon: ACG at 33-35 (2722500-2722502)	Score: 55.30
Possible intron: 37-43 (2722504-2722510)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GGCCGTGTGGCGAAATGGCATCGCGTCTGACTACGAaacgcgaATCAGGAGAtTGTAGGTTCGACCCCTACCTCGGTCA
Str: >>>>>.>..>>>>.......<<<<.>>>>>..............<<<<<.....>>>>>.......<<<<<<.<<<<<.

Chr_5.trna9 (2846111-2846183)	Length: 73 bp
Type: Met	Anticodon: CAT at 34-36 (2846144-2846146)	Score: 67.99
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: AGCAACATAGCTCAGGTGGTAGAGCGCGGGGCTCATAACCCCGAGGtCACTCGATCGAGACGAGTTGTTGCTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna10 (2849551-2849647)	Length: 97 bp
Type: Pro	Anticodon: AGG at 33-35 (2849583-2849585)	Score: 56.58
Possible intron: 37-61 (2849587-2849611)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GGCCTGATGGTCTAGTAGTATGATTCCTTGTTAGGGaaatggccttgccaaatccggtaaaTCGAGGAGGtCCCGGGTTCAATTCCCGGTCAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna11 (2873040-2873113)	Length: 74 bp
Type: Ile	Anticodon: GAT at 33-35 (2873072-2873074)	Score: 25.81
Possible pseudogene:  HMM Sc=29.42	Sec struct Sc=-3.61
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCTACCTGGCCCAATGGTAGCGCGTATCGTCGATGgctACCAAAAGGtTGCAGGTTCGATCCGGCGGTGTTCG
Str: >>.>>>>..>>.>.......<.<<.>.>.>..........<.<.<.....>>.>>......<<.<<<<<<.<<.

Chr_5.trna12 (2918522-2918609)	Length: 88 bp
Type: Glu	Anticodon: CTC at 34-36 (2918555-2918557)	Score: 48.70
Possible intron: 38-53 (2918559-2918574)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCGGATATGGTGTAACGGCtAACATTGCCGCCTCTCAtctgtgagagctagtcCGCGGCAGCTCGGGGTTCGATTCCCCGTATCCGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna13 (3082353-3082445)	Length: 93 bp
Type: Arg	Anticodon: TCG at 33-35 (3082385-3082387)	Score: 70.29
Possible intron: 37-57 (3082389-3082409)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGCTACCTGGCGCAATGGTAGCGCGTTTGGCTTCGAtggcccaacgggtacccaaaaACCAAAAGGtTGCAGGTTCGATCCCTGCGGTGGTCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna14 (3172312-3172228)	Length: 85 bp
Type: Gln	Anticodon: TTG at 34-36 (3172279-3172277)	Score: 65.05
Possible intron: 38-50 (3172275-3172263)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGCGCTATAGTGTAGTGGTtATCACTCGGGATTTTGActgtggtctggaaTTCCCGAAACCCAGGTTCGAACCCTGGTAGCGCCT
Str: >>>>>>>..>>>..........<<<.>>>>>....................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna15 (3172074-3171990)	Length: 85 bp
Type: Gln	Anticodon: TTG at 34-36 (3172041-3172039)	Score: 65.37
Possible intron: 38-50 (3172037-3172025)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGTGCTATAGTGTAGTGGTtATCACTCGGGATTTTGActatgaactcaaaTTCCCGAAACCCAGGTTCGAACCCTGGTAGCACCT
Str: >>>>>>>..>>>..........<<<.>>>>>....................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna16 (3137865-3137779)	Length: 87 bp
Type: Arg	Anticodon: ACG at 33-35 (3137833-3137831)	Score: 56.33
Possible intron: 37-51 (3137829-3137815)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GGCCGTGTGGCGAAATGGCATCGCGTCTGACTACGAttcagaaacatcgcgATCAGGAGAtTGCAGGTTCGACCCCTGCCTCGGTCA
Str: >>>>>.>..>>>>.......<<<<.>>>>>......................<<<<<.....>>>>>.......<<<<<<.<<<<<.

Chr_5.trna17 (3094097-3094019)	Length: 79 bp
Type: Arg	Anticodon: ACG at 33-35 (3094065-3094063)	Score: 56.80
Possible intron: 37-43 (3094061-3094055)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GGCCGTGTGGCGAAATGGCATCGCGTCTGACTACGAaacgcgaATCAGGAGAtTGCAGGTTCGACCCCTGCCTCGGTCA
Str: >>>>>.>..>>>>.......<<<<.>>>>>..............<<<<<.....>>>>>.......<<<<<<.<<<<<.

Chr_5.trna18 (2876060-2875977)	Length: 84 bp
Type: Arg	Anticodon: TCG at 33-35 (2876028-2876026)	Score: 68.97
Possible intron: 37-48 (2876024-2876013)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCTACTTGGCGCAATGGTAGCGCGTTTGGCTTCGAtggccgatggttACCAAAAGGtTGTAGGTTCGAGTCCTGCAGTGGTCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>...................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna19 (2795323-2795245)	Length: 79 bp
Type: Arg	Anticodon: ACG at 33-35 (2795291-2795289)	Score: 55.30
Possible intron: 37-43 (2795287-2795281)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GGCCGTGTGGCGAAATGGCATCGCGTCTGACTACGAaacgcgaATCAGGAGAtTGTAGGTTCGACCCCTACCTCGGTCA
Str: >>>>>.>..>>>>.......<<<<.>>>>>..............<<<<<.....>>>>>.......<<<<<<.<<<<<.

Chr_5.trna20 (2729910-2729832)	Length: 79 bp
Type: Arg	Anticodon: ACG at 33-35 (2729878-2729876)	Score: 55.30
Possible intron: 37-43 (2729874-2729868)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GGCCGTGTGGCGAAATGGCATCGCGTCTGACTACGAaacgcgaATCAGGAGAtTGTAGGTTCGACCCCTACCTCGGTCA
Str: >>>>>.>..>>>>.......<<<<.>>>>>..............<<<<<.....>>>>>.......<<<<<<.<<<<<.

Chr_5.trna21 (2603935-2603862)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (2603901-2603899)	Score: 77.15
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGTCTAGTTGGTcATGATTTCTGTCTAACACACAGAAGGtCCCCAGTTCGAACCTGGGTCGAACCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna22 (2603791-2603719)	Length: 73 bp
Type: Val	Anticodon: TAC at 34-36 (2603758-2603756)	Score: 74.01
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGTTCAATGGTCTAGTGGTtATGATTTCTGTCTTACACACAGAAGGtCTCCAGTTCGATCCTGGATTGAACCA
Str: >>>>>>>..>>>..........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna23 (1728384-1728305)	Length: 80 bp
Type: Gln	Anticodon: CTG at 34-36 (1728351-1728349)	Score: 65.03
Possible intron: 38-45 (1728347-1728340)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GGCTCTGTAGTGTAGCGGTtATCACTCAAGATTCTGAtcatcgacTTCTTGAAACCCAGGTTCGATTCCTGGCAGGGCCT
Str: >>>>>>>..>>>..........<<<.>>>>>...............<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna24 (1296791-1296702)	Length: 90 bp
Type: His	Anticodon: GTG at 34-36 (1296758-1296756)	Score: 48.45
Possible intron: 38-55 (1296754-1296737)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GTCCGTATCGATTAGGGGTtAAATCACTTCGTTGTGGttgccatgtgcacaagctCCGAAGAGCCGCTGGTTCGATTCCAGCTACGGACA
Str: >>>>>>>..>>>>........<<<<.>>>>>.........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna25 (532952-532860)	Length: 93 bp
Type: Leu	Anticodon: CAG at 35-37 (532918-532916)	Score: 59.31
Possible intron: 39-51 (532914-532902)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGCAATATGGCCGAGTGGTctAAGGCGCCAGAATCAGGtcgtaaagcacgtATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTGTTGTCA
Str: >>>>>>>..>>>...........<<<.>>>>>....................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_5.trna26 (490805-490690)	Length: 116 bp
Type: Pro	Anticodon: CGG at 33-35 (490773-490771)	Score: 53.83
Possible intron: 37-80 (490769-490726)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCCTGATGGTCTAGTAGCATGATTCCTCGTTCGGGtctacttttcgcgagaccacagagcacactcaagttctggaaatTCGAGGAGGtCCCGGGTTCAATTCCCGGTCAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>...................................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna27 (221108-221023)	Length: 86 bp
Type: Gly	Anticodon: GCC at 33-35 (221076-221074)	Score: 49.56
Possible intron: 37-51 (221072-221058)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GCATCAATGGGGTAGTGGTAACCTGGATCGTTGCCActctacgaccttgacTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_5.trna28 (9778-9683)	Length: 96 bp
Type: Cys	Anticodon: GCA at 33-35 (9746-9744)	Score: 20.41
Possible intron: 37-58 (9742-9721)
Possible pseudogene:  HMM Sc=2.79	Sec struct Sc=17.62
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: TCGGGTATAGCATAAAGCTAGTGCGGCACAACGCAGcttctactctggtgggtatgaaCTGTGGTGCACGTCGGGGTTCGATTCCCCGTATTCGAG
Str: >>>>>>>..>>>>.......<<<<..>>>>.............................<<<<........>>>>>.......<<<<<<<<<<<<.

Chr_6.trna1 (203950-204022)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (203983-203985)	Score: 60.68
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCGGATAGCTCAGTGGTtAGAGCATCCACCTAGTGTTGGGACGGtCCTCGGTTCAATCCCGGGTCTGGTCG
Str: >>>>>>>..>>>>........<<<<.>>>...........<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_6.trna2 (267717-267789)	Length: 73 bp
Type: Thr	Anticodon: TGT at 34-36 (267750-267752)	Score: 58.14
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCATATAGCTCAGTGGTtAGAGCGTCCCTCATGTGTAGAGGAGGtCTCTGGTTCAAATCCGGATGTGGTCA
Str: >>>>>>>..>>>>........<<<<.>>.>>.......<<.<<.....>>>>>.......<<<<<<<<<<<<.

Chr_6.trna3 (268657-268729)	Length: 73 bp
Type: Thr	Anticodon: TGT at 34-36 (268690-268692)	Score: 58.14
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCATATAGCTCAGTGGTtAGAGCGTCCCTCATGTGTAGAGGAGGtCTCTGGTTCAAATCCGGATGTGGTCA
Str: >>>>>>>..>>>>........<<<<.>>.>>.......<<.<<.....>>>>>.......<<<<<<<<<<<<.

Chr_6.trna4 (274431-274496)	Length: 66 bp
Type: Met	Anticodon: CAT at 32-34 (274462-274464)	Score: 34.33
         *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GACCATATAGCTCAGTGGTtAGAGCGTCCCTCATGTGTAGAGGAGGTTCAATTCCGGATGTGGTCA
Str: >>>>>>>..>>>>........<<<<.>>>.......<..<<...>>.......<<...<<<<<<<.

Chr_6.trna5 (1069708-1069800)	Length: 93 bp
Type: Ser	Anticodon: TGA at 34-36 (1069741-1069743)	Score: 62.92
Possible intron: 38-48 (1069745-1069755)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GCTGGAATGGCCGAGTCGTtAAGGCGAGTGATTTGAAttttcaaacttATCACTTGGTGTTTCACCGCGTAGGTTCAAATCCTGCTTCCAGCG
Str: >>>>>>>..>>>..........<<<.>>>>>..................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_6.trna6 (1363487-1363581)	Length: 95 bp
Type: Ser	Anticodon: AGA at 34-36 (1363520-1363522)	Score: 66.98
Possible intron: 38-50 (1363524-1363536)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GACACCGTAGCCAAGTGGTtACGGCGACAGATTAGAAtacccttctagccATCTGTTTCACTTTGTGAGCACAGGTTCGAATCCTGTCGGTGTCG
Str: >>>>>>>..>>>..........<<<.>>>>>....................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_6.trna7 (1400056-1400146)	Length: 91 bp
Type: Ala	Anticodon: CGC at 34-36 (1400089-1400091)	Score: 66.45
Possible intron: 38-55 (1400093-1400110)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GGGCACTTGGCACAGTTGGTAGCGCGCTCGCTTCGCAtccctcgagatcgaatatTGCGTGAGGtCGTGGGTTCAATTCCCACAGTGTCCA
Str: >>>>>>>..>>.>........<.<<.>.>>>.........................<<<.<.....>>>>>.......<<<<<<<<<<<<.

Chr_6.trna8 (1656421-1656561)	Length: 141 bp
Type: Leu	Anticodon: AAG at 35-37 (1656455-1656457)	Score: 55.71
Possible intron: 39-99 (1656459-1656519)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GGTGAGATGGCCGAGCGGTctAAGGCGCCAGACTAAGGaccagcgcgttctacgtgcacacctccagcgttcaattcccactcaggttctgaacacattATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTCTCATCA
Str: >>>>>>>..>>>...........<<<.>>>>>....................................................................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_6.trna9 (1701471-1701558)	Length: 88 bp
Type: Gly	Anticodon: GCC at 33-35 (1701503-1701505)	Score: 50.87
Possible intron: 37-53 (1701507-1701523)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: GCATCAATGGGGTAGTGGTAACCTGGATCGTTGCCActcatatcgagattgacTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_6.trna10 (1676502-1676416)	Length: 87 bp
Type: Gly	Anticodon: GCC at 33-35 (1676470-1676468)	Score: 47.34
Possible intron: 37-52 (1676466-1676451)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GCATTAATGGGGTAGTGGTAACCTGGATCGTTGCCActctaacgagttcgacTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_6.trna11 (1406945-1406841)	Length: 105 bp
Type: Ala	Anticodon: TGC at 34-36 (1406912-1406910)	Score: 66.84
Possible intron: 38-69 (1406908-1406877)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGGCGCTTGGCGCAGTTGGTAGCGCGTCTGCTTTGCAtcgtctcaagcttggctttggatagcaaaattTGCATAAGGtCATGGGTTCAAATCCCATAGCGTCCA
Str: >>>>>>>..>>>>........<<<<.>.>>>.......................................<<<.<.....>>>>>.......<<<<<<<<<<<<.

Chr_6.trna12 (1362911-1362822)	Length: 90 bp
Type: Ala	Anticodon: CGC at 34-36 (1362878-1362876)	Score: 66.95
Possible intron: 38-54 (1362874-1362858)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GGGCACTTGGCACAGTTGGTAGCGCGCTCGCTTCGCAtcctcgagatcgaatatTGCGTGAGGtCGTGGGTTCAATTCCCACAGTGTCCA
Str: >>>>>>>..>>.>........<.<<.>.>>>........................<<<.<.....>>>>>.......<<<<<<<<<<<<.

Chr_6.trna13 (1130038-1129946)	Length: 93 bp
Type: Ser	Anticodon: TGA at 34-36 (1130005-1130003)	Score: 61.94
Possible intron: 38-48 (1130001-1129991)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GCTGGAATGGCCGAGTCGTtAAGGCGAGTGATTTGAAtacccaaacatATCACTTGGTGTTTCACCGCGTAGGTTCAAATCCTGCTTCCAGCG
Str: >>>>>>>..>>>..........<<<.>>>>>..................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_6.trna14 (1110231-1110136)	Length: 96 bp
Type: Ser	Anticodon: AGA at 34-36 (1110198-1110196)	Score: 67.60
Possible intron: 38-51 (1110194-1110181)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GACACCGTAGCCAAGTGGTtACGGCGACAGATTAGAAttccacttctatccATCTGTTTCACTTTGTGAGCACAGGTTCGAATCCTGTCGGTGTCG
Str: >>>>>>>..>>>..........<<<.>>>>>.....................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

Chr_6.trna15 (81560-81488)	Length: 73 bp
Type: Cys	Anticodon: ACA at 34-36 (81527-81525)	Score: 20.00
Possible pseudogene:  HMM Sc=16.50	Sec struct Sc=3.50
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGCGCTGTAGTCAAGTGGTgACTTCGTTTCCTGACAAAGGAGACGtTGGGGGTTCGATTCCtCTGCAGCGACA
Str: >.>>>>>..>..............<.>>>>>.......<<<<<.....>>>>.......<<.<<.<<<<<.<.

Chr_7.trna1 (44324-44420)	Length: 97 bp
Type: Arg	Anticodon: TCG at 33-35 (44356-44358)	Score: 66.17
Possible intron: 37-61 (44360-44384)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GGCTACCTGGCGCAATGGTAGCGCGTTTGGCTTCGAtggcttaacggctcctttgatggttACCAAAAGGtTGTAGGTTCGAGTCCTGCGGTGGTCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna2 (67398-67481)	Length: 84 bp
Type: Arg	Anticodon: TCG at 33-35 (67430-67432)	Score: 70.84
Possible intron: 37-48 (67434-67445)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCTACCTGGCGCAATGGTAGCGCGTTTGGCTTCGAtggctaaccggcACCAAAAGGtTGCAGGTTCGATCCCTGCGGTGGTCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>...................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna3 (423847-423920)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (423881-423883)	Score: 76.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCTTGGGTTCGATCCCCACGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<......>>>>.......<<<<.<<<<<<<.

Chr_7.trna4 (430336-430409)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (430370-430372)	Score: 76.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCTTGGGTTCGATCCCCACGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<......>>>>.......<<<<.<<<<<<<.

Chr_7.trna5 (525876-525949)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (525910-525912)	Score: 76.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCTTGGGTTCGATCCCCACGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<......>>>>.......<<<<.<<<<<<<.

Chr_7.trna6 (553681-553754)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (553715-553717)	Score: 76.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCTTGGGTTCGATCCCCACGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<......>>>>.......<<<<.<<<<<<<.

Chr_7.trna7 (570766-570887)	Length: 122 bp
Type: Val	Anticodon: AAC at 35-37 (570800-570802)	Score: 63.46
Possible intron: 39-86 (570804-570851)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GGGTCGATGGCGTAGTTGGTtATCGCATCTGTCTAACAaactggtgcggaaccgtgccttgtacgaggtacggttccgcacttggcCACAGAAGGtCGCCAGTTCGAACCTGGCTCGACTCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......................................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna8 (573149-573290)	Length: 142 bp
Type: Val	Anticodon: AAC at 35-37 (573183-573185)	Score: 59.07
Possible intron: 39-106 (573187-573254)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GGGTCGATGGCGTAGTTGGTtATCGCATCTGTCTAACAaccacccccttcttgccagcgctggcttgccttgtacgaggtactgctgttggcagatgggtgtggtcCACAGAAGGtCGCCAGTTCGAACCTGGCTCGACTCA
Str: >>>>>>>..>>>...........<<<.>>>>>...........................................................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna9 (762884-762957)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (762918-762920)	Score: 76.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCTTGGGTTCGATCCCCACGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<......>>>>.......<<<<.<<<<<<<.

Chr_7.trna10 (1120731-1120828)	Length: 98 bp
Type: Asn	Anticodon: GTT at 35-37 (1120765-1120767)	Score: 75.63
Possible intron: 39-62 (1120769-1120792)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TGCCCCATGGCTGAGTTGGTtACAGCGTCCGACTGTTAtagagcttttcaaggcttacttcaATCGGAAGGtCGTGAGTTCGAGCCTCACTGGGGCAG
Str: >>>>>>>..>>>>.........<<<<.>>>>>...............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna11 (1162711-1162782)	Length: 72 bp
Type: Gly	Anticodon: TCC at 34-36 (1162744-1162746)	Score: 75.25
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: ACACTCATGGTGAAGTGGTtATCATGCTTGCCTTCCAAGCAAGCGGCACGGGTTCGATTCCCGTTGAGTGTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna12 (1163364-1163435)	Length: 72 bp
Type: Gly	Anticodon: TCC at 34-36 (1163397-1163399)	Score: 75.25
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: ACACTCATGGTGAAGTGGTtATCATGCTTGCCTTCCAAGCAAGCGGCACGGGTTCGATTCCCGTTGAGTGTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna13 (1234669-1234754)	Length: 86 bp
Type: Pro	Anticodon: AGG at 33-35 (1234701-1234703)	Score: 57.24
Possible intron: 37-50 (1234705-1234718)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCCTGATGGTCTAGTAGTATGATTCCTTGTTAGGGagcatcagctcattTCGAGGAGGtCCCGGGTTCAATTCCCGGTCAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>.....................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna14 (1881362-1881434)	Length: 73 bp
Type: Thr	Anticodon: TGT at 34-36 (1881395-1881397)	Score: 49.77
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCATATAGCTCAGTGGTtAGAGCATCCCTCATGTGTAGAGGAGGtCTCTAGTTCAAATCCGGATGTGGTCA
Str: >>>>>>>..>>>>........<<<<.>>.>>.......<<.<<.....>>>.>.......<.<<<<<<<<<<.

Chr_7.trna15 (2423646-2423717)	Length: 72 bp
Type: Asp	Anticodon: GTC at 34-36 (2423679-2423681)	Score: 57.25
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCTCTGTTAGTATATCGGTtAGTACACGCGCCTGTCACGCGCGAAAGCTGGGTTCGACTCCCAGACAGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna16 (2464482-2464555)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (2464516-2464518)	Score: 64.08
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCAAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTTGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna17 (2942867-2942958)	Length: 92 bp
Type: Asp	Anticodon: GTC at 34-36 (2942900-2942902)	Score: 49.05
Possible intron: 38-57 (2942904-2942923)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCTCTGTTAGTATATCGGTtAGTACACGCGCCTGTCAtcgcatatcatgttattggcCGCGCGAAAGCTGGGTTCGACTCCCAGACAGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>...........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna18 (2953686-2953774)	Length: 89 bp
Type: Tyr	Anticodon: GTA at 34-36 (2953719-2953721)	Score: 63.79
Possible intron: 38-53 (2953723-2953738)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: CCGACCTTAGCTCAGTTGGAAGAGCGCAAGACTGTAAttggtgaaccgaggtcATCTTGATGtCGCCTGTTCGAGCCAGGCAGGTCGGA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna19 (2940310-2940201)	Length: 110 bp
Type: Asp	Anticodon: GTC at 34-36 (2940277-2940275)	Score: 45.60
Possible intron: 38-75 (2940273-2940236)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: TCTCTGTTAGTATATCGGTtAGTACACGCGCCTGTCAtgcctgtgtggacgaaagaaagttccttcttccttggcCGCGCGAAAGCTGGGTTCGACTCCCAGACAGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>.............................................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna20 (2931404-2931332)	Length: 73 bp
Type: Met	Anticodon: CAT at 34-36 (2931371-2931369)	Score: 67.99
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: AGCAACATAGCTCAGGTGGTAGAGCGCGGGGCTCATAACCCCGAGGtCACTCGATCGAGACGAGTTGTTGCTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna21 (2891710-2891638)	Length: 73 bp
Type: Met	Anticodon: CAT at 34-36 (2891677-2891675)	Score: 67.99
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: AGCAACATAGCTCAGGTGGTAGAGCGCGGGGCTCATAACCCCGAGGtCACTCGATCGAGACGAGTTGTTGCTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna22 (2816466-2816394)	Length: 73 bp
Type: Met	Anticodon: CAT at 34-36 (2816433-2816431)	Score: 67.99
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: AGCAACATAGCTCAGGTGGTAGAGCGCGGGGCTCATAACCCCGAGGtCACTCGATCGAGACGAGTTGTTGCTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna23 (1900246-1900177)	Length: 70 bp
Type: Leu	Anticodon: CAG at 32-34 (1900215-1900213)	Score: 51.10
         *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GACCATATAGCTCAGTGGTtAGAGCGTCCCTCAGTAGAGGAGGtCTCTGGTTCAATTCCGGATGTGGTCT
Str: >>>>>>>..>>>>........<<<<.>>>.......<.<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna24 (1384102-1384017)	Length: 86 bp
Type: Pro	Anticodon: AGG at 33-35 (1384070-1384068)	Score: 56.80
Possible intron: 37-50 (1384066-1384053)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCCTGATGGTCTAGTAGTATGATTCCTTGTTAGGGtgtttctgctcgttTCGAGGAGGtCCCGGGTTCAATTCCCGGTCAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>.....................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna25 (1239537-1239452)	Length: 86 bp
Type: Pro	Anticodon: AGG at 33-35 (1239505-1239503)	Score: 56.74
Possible intron: 37-50 (1239501-1239488)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GGCCTGATGGTCTAGTAGTATGATTCCTTGTTAGGGagcaccagctcataTCGAGGAGGtCCCGGGTTCAATTCCCGGTCAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>.....................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna26 (1172936-1172865)	Length: 72 bp
Type: Gly	Anticodon: TCC at 34-36 (1172903-1172901)	Score: 76.40
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: ACACCGATGGTGAAGTGGTtATCATGCTTGCCTTCCAAGCAAGCGGCACGGGTTCGATTCCCGTTCGGTGTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna27 (1172654-1172583)	Length: 72 bp
Type: Gly	Anticodon: TCC at 34-36 (1172621-1172619)	Score: 76.40
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: ACACCGATGGTGAAGTGGTtATCATGCTTGCCTTCCAAGCAAGCGGCACGGGTTCGATTCCCGTTCGGTGTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna28 (952479-952408)	Length: 72 bp
Type: Glu	Anticodon: TTC at 34-36 (952446-952444)	Score: 59.98
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCCGATATGGTGTAACGGCtAACATTACCGCCTTTCACGCGGTAGCTCGGGGTTCGATTCCCCGTGTCGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna29 (948229-948128)	Length: 102 bp
Type: Pro	Anticodon: AGG at 32-34 (948198-948196)	Score: 21.98
Possible intron: 35-68 (948195-948162)
Possible pseudogene:  HMM Sc=1.58	Sec struct Sc=20.40
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GCCCGGTAGCGTAGCGGTaATCGCTCCCGAGAGGttcatgctcccacaattgggattgacagaaccggCTCGGGAAGCCCTGTTCGACTCAGGGACTGGGCA
Str: >>>>>>>.>>>..........<<<.>>>>>.......................................<<<<<...>>>>>.......<<<<<<<<<<<<.

Chr_7.trna30 (507977-507896)	Length: 82 bp
Type: Asn	Anticodon: GTT at 35-37 (507943-507941)	Score: 76.43
Possible intron: 39-46 (507939-507932)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TGCCCCATGGCTGAGTTGGTtACAGCGTCCGACTGTTAttgtgactATCGGAAGGtCGTGAGTTCGAGCCTCACTGGGGCAG
Str: >>>>>>>..>>>>.........<<<<.>>>>>...............<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_7.trna31 (458432-458359)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (458398-458396)	Score: 76.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCTTGGGTTCGATCCCCACGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<......>>>>.......<<<<.<<<<<<<.

Chr_7.trna32 (149402-149319)	Length: 84 bp
Type: Arg	Anticodon: TCG at 33-35 (149370-149368)	Score: 70.84
Possible intron: 37-48 (149366-149355)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCTACCTGGCGCAATGGTAGCGCGTTTGGCTTCGAtggctaaccggcACCAAAAGGtTGCAGGTTCGATCCCTGCGGTGGTCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>...................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna1 (691318-691402)	Length: 85 bp
Type: Gln	Anticodon: TTG at 34-36 (691351-691353)	Score: 63.70
Possible intron: 38-50 (691355-691367)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGCGTTATAGTGTAGTGGTtATCACTCGGGATTTTGAcctctcatcaatcTTCCCGAAACCCAGGTTCGAACCCTGGTAACGCCT
Str: >>>>>>>..>>>..........<<<.>>>>>....................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna2 (708202-708289)	Length: 88 bp
Type: Gln	Anticodon: TTG at 34-36 (708235-708237)	Score: 64.01
Possible intron: 38-53 (708239-708254)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: GGCGTTATAGTGTAGTGGTtATCACTCGGGATTTTGActacataccagcaatcTTCCCGAAACCCAGGTTCGAACCCTGGTAACGCCT
Str: >>>>>>>..>>>..........<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna3 (1095754-1095840)	Length: 87 bp
Type: Pro	Anticodon: TGG at 33-35 (1095786-1095788)	Score: 55.20
Possible intron: 37-51 (1095790-1095804)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GGCCTTATGGTCTAGTAGTATGATTCCTCGTTTGGGtattgcttgcctaatTCGAGGAGGtCCTGGGTTCAACTCCCAGTGAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>......................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna4 (1492534-1492607)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (1492568-1492570)	Score: 79.94
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGCGTAGTTGGTtATCGCATCTGTCTAACACACAGAAGGtCGCCAGTTCGAACCTGGCTCGAATCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna5 (1688012-1688083)	Length: 72 bp
Type: Glu	Anticodon: TTC at 34-36 (1688045-1688047)	Score: 59.98
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCCGATATGGTGTAACGGCtAACATTACCGCCTTTCACGCGGTAGCTCGGGGTTCGATTCCCCGTGTCGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna6 (1688169-1688240)	Length: 72 bp
Type: Glu	Anticodon: TTC at 34-36 (1688202-1688204)	Score: 59.98
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCCGATATGGTGTAACGGCtAACATTACCGCCTTTCACGCGGTAGCTCGGGGTTCGATTCCCCGTGTCGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna7 (2497880-2497963)	Length: 84 bp
Type: Ala	Anticodon: CGC at 33-35 (2497912-2497914)	Score: 69.40
Possible intron: 37-48 (2497916-2497927)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCGTTTGGCACAGTGGTAGCGCGTTCGCTTCGCAtttattgacgctTGCGAAAGGtCCAGGGTTCAATCCCCTGAACGTCCA
Str: >>>>>>>..>>.>.......<.<<.>>>>>...................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna8 (2500504-2500590)	Length: 87 bp
Type: Ser	Anticodon: GCT at 33-35 (2500536-2500538)	Score: 25.59
Possible intron: 37-44 (2500540-2500547)
Possible pseudogene:  HMM Sc=5.08	Sec struct Sc=20.51
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: TCGGGTATAGCATAAAGGTAGTGCACCACAGCGCTGtccgcaggATATGGCTGCTAGGATGTCGGGGTTCGATTCCCCGTACTCGAA
Str: >>>>>>>..>>>>.......<<<<.>>>.>...............<.<<<..>.>..<.<..>>>>>.......<<<<<<<<<<<<.

Chr_8.trna9 (2386561-2386489)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (2386528-2386526)	Score: 60.68
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCGGATAGCTCAGTGGTtAGAGCATCCACCTAGTGTTGGGACGGtCCTCGGTTCAATCCCGGGTCTGGTCG
Str: >>>>>>>..>>>>........<<<<.>>>...........<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna10 (1505981-1505901)	Length: 81 bp
Type: Cys	Anticodon: GCA at 33-35 (1505949-1505947)	Score: 67.57
Possible intron: 37-45 (1505945-1505937)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GTCTCGATAGCTAAGTGGTATAGCGTGCGATTGCAAtgtgttaatATCGCGAGGtCCCGTGTTCGAACCACGGTCGGGACT
Str: >>>>>>>..>>>>.......<<<<.>>>>>................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_8.trna11 (546481-546398)	Length: 84 bp
Type: His	Anticodon: GTG at 34-36 (546448-546446)	Score: 40.42
Possible intron: 38-49 (546444-546433)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GTCCTTGTCGATTAGTGGTtAAATCATCTCGTTGTGGctctgattcgctCCGAGAAGCCGGAAGTTCGAATCCTCCCTGGGACA
Str: >>>>>.>..>>>>........<<<<.>>>>>...................<<<<<....>>>.>.......<.<<<<.<<<<<.

Chr_8.trna12 (37133-37050)	Length: 84 bp
Type: Asp	Anticodon: GTC at 34-36 (37100-37098)	Score: 50.98
Possible intron: 38-49 (37096-37085)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: TCTCCGTTAGTATATCGGTtAGTACACGCGCCTGTCAtctcaatatggcCGCGCGAAAGCTGGGTTCGACTCCCAGACGGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>...................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_9.trna1 (581651-581722)	Length: 72 bp
Type: Gly	Anticodon: TCC at 34-36 (581684-581686)	Score: 75.25
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: ACACTCATGGTGAAGTGGTtATCATGCTTGCCTTCCAAGCAAGCGGCACGGGTTCGATTCCCGTTGAGTGTA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_9.trna2 (1524442-1524539)	Length: 98 bp
Type: Arg	Anticodon: CCT at 33-35 (1524474-1524476)	Score: 56.59
Possible intron: 37-62 (1524478-1524503)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: GCCAACGTAGCACAATGGTAGTGCGTTGCTTTCCTAcctgtagcccttggggttagggttcaAGGCAAAGGtTGTGGGTTCGATCCCCATCGTTGGTT
Str: >>>>>>>..>>>>.......<<<<.>>>>>.................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_9.trna3 (2021544-2021637)	Length: 94 bp
Type: Asn	Anticodon: GTT at 35-37 (2021578-2021580)	Score: 73.84
Possible intron: 39-58 (2021582-2021601)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: TGCCCCATGGCTGAGTTGGTtACAGCGTCCGACTGTTAgcgactttggttggcagactATCGGAAGGtCGTGAGTTCGAGCCTCACTGGGGCAG
Str: >>>>>>>..>>>>.........<<<<.>>>>>...........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_9.trna4 (2297870-2297942)	Length: 73 bp
Type: Thr	Anticodon: TGT at 34-36 (2297903-2297905)	Score: 54.28
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCATATAGCTCAGTGGTtAGAGCGTCCCTCATGTGTAGAGGAAGtCTCTGGTTCAATTCCGGATGTGGTCA
Str: >>>>>>>..>>>>........<<<<.>>.>>.......<<.<<.....>>>>>.......<<<<<<<<<<<<.

Chr_9.trna5 (1873619-1873525)	Length: 95 bp
Type: Ala	Anticodon: AGC at 35-37 (1873585-1873583)	Score: 56.18
Possible intron: 39-59 (1873581-1873561)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGGCACATGGTGTAGTTGGTtATCACATCCGCTTAGCAtttcacagcccgtgaattggtTGCGGGGGGtGTCCGGTTCAATTCCGGATGTGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_9.trna6 (1550267-1550170)	Length: 98 bp
Type: Thr	Anticodon: CGT at 33-35 (1550235-1550233)	Score: 69.64
Possible intron: 37-62 (1550231-1550206)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: GCCCTCTTAGCTCAGTGGTAGAGCGCACCACTCGTAcgagcttgaaaagcttcgaacaagcaATGGTGAGGtCGGTTGTTCAATCCAGCCAGGGGGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_9.trna7 (356065-355993)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (356032-356030)	Score: 60.68
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCGGATAGCTCAGTGGTtAGAGCATCCACCTAGTGTTGGGACGGtCCTCGGTTCAATCCCGGGTCTGGTCG
Str: >>>>>>>..>>>>........<<<<.>>>...........<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_9.trna8 (355778-355706)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (355745-355743)	Score: 60.68
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCGGATAGCTCAGTGGTtAGAGCATCCACCTAGTGTTGGGACGGtCCTCGGTTCAATCCCGGGTCTGGTCG
Str: >>>>>>>..>>>>........<<<<.>>>...........<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna1 (50986-51084)	Length: 99 bp
Type: Ala	Anticodon: GGC at 36-38 (51021-51023)	Score: 30.73
Possible intron: 40-63 (51025-51048)
Possible pseudogene:  HMM Sc=44.39	Sec struct Sc=-13.66
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GCCTTTTTGGCTCAGTTGGTttATCGCGAGTTGCTGGCGcggtttctaacagtatcaccggttACCATTAGGtCGCAGGTTCAAACCCTGGCAGGTGCA
Str: >>.>>>...>>..............<<.>>>.>...............................<.<<<......>>>>.......<<<<..<<<.<<.

Chr_10.trna2 (188654-188750)	Length: 97 bp
Type: Pro	Anticodon: TGG at 33-35 (188686-188688)	Score: 58.61
Possible intron: 37-61 (188690-188714)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    * 
Seq: GGCCTTATGGTCTAGTCGTATGATTCCTCGTTTGGGttgacaattatgtctatgtctcataTCGAGGAGGtCCTGGGTTCAATTCCCAGTGAGGCCC
Str: >>>>>>>..>>>.........<<<.>>>>>................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna3 (1250543-1250616)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (1250577-1250579)	Score: 65.62
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCCAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTGGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna4 (1263407-1263480)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (1263441-1263443)	Score: 65.62
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCCAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTGGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna5 (1263934-1264007)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (1263968-1263970)	Score: 65.62
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCCAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTGGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna6 (1808640-1808735)	Length: 96 bp
Type: Asn	Anticodon: GTT at 35-37 (1808674-1808676)	Score: 72.19
Possible intron: 39-60 (1808678-1808699)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: TGCCCCATGGCTGAGTTGGTtACAGCGTCCGACTGTTAttaagcgcccgttcgcgtggcaATCGGAAGGtCGTGAGTTCGAGCCTCACTGGGGCAG
Str: >>>>>>>..>>>>.........<<<<.>>>>>.............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna7 (2110566-2110651)	Length: 86 bp
Type: Tyr	Anticodon: GTA at 34-36 (2110599-2110601)	Score: 62.92
Possible intron: 38-50 (2110603-2110615)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: CCGACCTTAGCTCAGCTGGAAGAGCACGAGACTGTAAttggttgcattgaATCTCGGGGtCGCCTGTTCGAGCCAGGCAGGTCGGA
Str: >>>>>>>..>>>>........<<<<.>>>>>....................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna8 (2155034-2155124)	Length: 91 bp
Type: Ala	Anticodon: TGC at 33-35 (2155066-2155068)	Score: 64.31
Possible intron: 37-55 (2155070-2155088)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GGGCGTTTGGCACAGTGGTAGCGCGTTCGCTTTGCAtggtcgtttagattcagctTGCGAAAAGtCCAGGGTTCAATCCCCTGAACGTCCA
Str: >>>>>>>..>>.>.......<.<<.>>>>>..........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna9 (1304073-1303970)	Length: 104 bp
Type: Met	Anticodon: CAT at 35-37 (1304039-1304037)	Score: 70.13
Possible intron: 39-68 (1304035-1304006)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GCCTTCTTGGCTCAGTTGGCtAGAGCGCAGGTCTCATAtttcggtatgagtgagcattggctcataaaATCCTGAGGtCGCAAGTTCGAGCCTTGCAGGGGGCA
Str: >>>>>>>..>>>>.........<<<<.>>>>.......................................<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna10 (1264648-1264575)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (1264614-1264612)	Score: 65.62
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCCAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTGGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna11 (1262882-1262809)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (1262848-1262846)	Score: 65.62
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCCAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTGGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna12 (1250027-1249954)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (1249993-1249991)	Score: 65.62
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCCAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTGGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna13 (1248935-1248862)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (1248901-1248899)	Score: 64.08
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCAAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTTGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna14 (1087298-1087225)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (1087264-1087262)	Score: 64.08
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCAAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTTGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna15 (748884-748811)	Length: 74 bp
Type: Ala	Anticodon: AGC at 35-37 (748850-748848)	Score: 64.08
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGGCAAATGGTGTAGTTGGTtATCACATCCGCTTAGCATGCGGGGGGtGTCCGGTTCAATTCCGGATTTGTCCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_10.trna16 (124908-124836)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (124875-124873)	Score: 73.61
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TCCTTCTTAGCTCAGTTGGTAGAGCGCGTCACTAGTAATGACGAGGtCAGTCGTTCGAGTCGGCTAGAAGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna1 (452129-452207)	Length: 79 bp
Type: Arg	Anticodon: ACG at 33-35 (452161-452163)	Score: 55.30
Possible intron: 37-43 (452165-452171)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GGCCGTGTGGCGAAATGGCATCGCGTCTGACTACGAaacgcgaATCAGGAGAtTGTAGGTTCGACCCCTACCTCGGTCA
Str: >>>>>.>..>>>>.......<<<<.>>>>>..............<<<<<.....>>>>>.......<<<<<<.<<<<<.

Chr_11.trna2 (554939-555037)	Length: 99 bp
Type: Ala	Anticodon: GGC at 36-38 (554974-554976)	Score: 30.73
Possible intron: 40-63 (554978-555001)
Possible pseudogene:  HMM Sc=44.39	Sec struct Sc=-13.66
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: GCCTTTTTGGCTCAGTTGGTttATCGCGAGTTGCTGGCGcggtttctaacagtatcaccggttACCATTAGGtCGCAGGTTCAAACCCTGGCAGGTGCA
Str: >>.>>>...>>..............<<.>>>.>...............................<.<<<......>>>>.......<<<<..<<<.<<.

Chr_11.trna3 (686237-686340)	Length: 104 bp
Type: Leu	Anticodon: AAG at 35-37 (686271-686273)	Score: 60.74
Possible intron: 39-62 (686275-686298)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTGAGATGGCCGAGCGGTctAAGGCGCCAGACTAAGGatcagcctgcattgcaggcacggtATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTCTCATCA
Str: >>>>>>>..>>>...........<<<.>>>>>...............................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_11.trna4 (700281-700376)	Length: 96 bp
Type: Arg	Anticodon: CCT at 33-35 (700313-700315)	Score: 60.10
Possible intron: 37-60 (700317-700340)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GCCAACGTAGCACAATGGTAGTGCGTTGCTTTCCTAcctaaaaaggaaataggtcacgtgAGGCAAAGGtTGTGGGTTCGATCCCCATCGTTGGTT
Str: >>>>>>>..>>>>.......<<<<.>>>>>...............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna5 (878603-878690)	Length: 88 bp
Type: Asp	Anticodon: GTC at 34-36 (878636-878638)	Score: 47.58
Possible intron: 38-53 (878640-878655)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCTCTGTTAGTATATAGGTtAGTACACGCGCCTGTCAttagtacttgctgtgaCGCGCGAAAGCTGGGTTCGACTCCCAGACAGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna6 (879112-879195)	Length: 84 bp
Type: Asp	Anticodon: GTC at 34-36 (879145-879147)	Score: 49.38
Possible intron: 38-49 (879149-879160)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: TCTCTGTTAGTATATCGGTtAGTACACGCGCCTGTCAtcctatctgtgaCGCGCGAAAGCTGGGTTCGACTCCCAGACAGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>...................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna7 (883977-884065)	Length: 89 bp
Type: Asp	Anticodon: GTC at 34-36 (884010-884012)	Score: 52.53
Possible intron: 38-54 (884014-884030)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *   
Seq: TCTCCGTTAGTATATCGGTtAGTACACGCGCCTGTCAttgattgcttatcaataCGCGCGAAAGCTGGGTTCGACTCCCAGACGGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>........................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna8 (917968-918040)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (918001-918003)	Score: 73.61
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TCCTTCTTAGCTCAGTTGGTAGAGCGCGTCACTAGTAATGACGAGGtCAGTCGTTCGAGTCGGCTAGAAGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna9 (1025469-1025548)	Length: 80 bp
Type: Leu	Anticodon: CAG at 35-37 (1025503-1025505)	Score: 66.33
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: GGCGAGATGGCCGAGCGGTctAAGGCGCCAGAATCAGGATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTCTCGTCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_11.trna10 (1028145-1028249)	Length: 105 bp
Type: Leu	Anticodon: AAG at 35-37 (1028179-1028181)	Score: 62.75
Possible intron: 39-63 (1028183-1028207)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGCGAGATGGCCGAGCGGTctAAGGCGCCAGACTAAGGatcagcctgcattggcaggcaaggtATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTCTCGTCA
Str: >>>>>>>..>>>...........<<<.>>>>>................................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_11.trna11 (1135924-1135996)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (1135957-1135959)	Score: 60.68
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCGGATAGCTCAGTGGTtAGAGCATCCACCTAGTGTTGGGACGGtCCTCGGTTCAATCCCGGGTCTGGTCG
Str: >>>>>>>..>>>>........<<<<.>>>...........<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna12 (1141168-1141265)	Length: 98 bp
Type: Ala	Anticodon: GGC at 36-38 (1141203-1141205)	Score: 22.41
Possible intron: 40-62 (1141207-1141229)
Possible pseudogene:  HMM Sc=42.12	Sec struct Sc=-19.71
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: GCCTTTTTGGCTCAGTTGGTttATCGCGAGTTGCTGGCGcggtttctaacagtatcaccggtTGCATTAGGtCGCAGGTTCAAACCCTGGCAGGTGCA
Str: >>.>>>...>>..............<<.>>>..................................<<<......>>>>.......<<<<..<<<.<<.

Chr_11.trna13 (1152056-1152128)	Length: 73 bp
Type: Thr	Anticodon: TGT at 34-36 (1152089-1152091)	Score: 57.16
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACCGTATAGCTCAGTGGTtAGAGCGTCCCTCATGTGTAGAGGAGGtCTCTGGTTCAATTCCGGATGTGGTCA
Str: >>>>>>>..>>>>........<<<<.>>.>>.......<<.<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna14 (1334014-1334086)	Length: 73 bp
Type: Val	Anticodon: TAC at 34-36 (1334047-1334049)	Score: 74.01
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGTTCAATGGTCTAGTGGTtATGATTTCTGTCTTACACACAGAAGGtCTCCAGTTCGATCCTGGATTGAACCA
Str: >>>>>>>..>>>..........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna15 (1862400-1862492)	Length: 93 bp
Type: Ala	Anticodon: TGC at 33-35 (1862432-1862434)	Score: 62.67
Possible intron: 37-57 (1862436-1862456)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGGCGTTTGGCACAGTGGTAGCGCGTTCGCTTTGCAttgacactctccagtcgagctTGCGAAAAGtCCAGGGTTCAATCCCCTGAACGTCCA
Str: >>>>>>>..>>.>.......<.<<.>>>>>............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna16 (1413817-1413722)	Length: 96 bp
Type: Arg	Anticodon: CCT at 33-35 (1413785-1413783)	Score: 51.31
Possible intron: 37-60 (1413781-1413758)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *
Seq: GCCAACGTAGCACAATGGTAGTGCGTTGCTTTCCTAtccttgggttaagcgcccaaaaagAGGCAGAGGcTGTGGGTTCGAGTCCCATCGTTGGTT
Str: >>>>>>>..>>>>.......<<<<.>>>>>...............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna17 (1371633-1371551)	Length: 83 bp
Type: Val	Anticodon: CAC at 34-36 (1371600-1371598)	Score: 66.39
Possible intron: 38-47 (1371596-1371587)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGTTCAATGGTCTAGTGGTtATGATTTCTGTCTCACAtgctcgtgaaCACAGAAGGtCTCCAGTTCGATCCTGGATTGAACCA
Str: >>>>>>>..>>>..........<<<.>>>>>.................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna18 (1331080-1330998)	Length: 83 bp
Type: Val	Anticodon: CAC at 34-36 (1331047-1331045)	Score: 70.99
Possible intron: 38-47 (1331043-1331034)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GGTTGAATGGTCTAGTGGTtATGATTTCTGTCTCACAtgaatgtgatCACAGAAGGtCCCCAGTTCGATCCTGGGTTCAACCA
Str: >>>>>>>..>>>..........<<<.>>>>>.................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna19 (1302479-1302387)	Length: 93 bp
Type: His	Anticodon: GTG at 34-36 (1302446-1302444)	Score: 48.61
Possible intron: 38-58 (1302442-1302422)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GTCCGTATCGATTAGGGGTtAAATCACTTCGTTGTGGagagcctttgggcgatcaattCCGAAGAGCCGCTGGTTCGATTCCAGCTACGGACA
Str: >>>>>>>..>>>>........<<<<.>>>>>............................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna20 (1030884-1030780)	Length: 105 bp
Type: Leu	Anticodon: AAG at 35-37 (1030850-1030848)	Score: 62.12
Possible intron: 39-63 (1030846-1030822)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGCGAGATGGCCGAGCGGTctAAGGCGCCAGACTAAGGaccagcctgcattggcaggcaaggtATCTGGTCCGAAAGGGCGTGGGTTCGAATCCCACTCTCGTCA
Str: >>>>>>>..>>>...........<<<.>>>>>................................<<<<<.>>....<<..>>>>>.......<<<<<<<<<<<<.

Chr_11.trna21 (929483-929411)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (929450-929448)	Score: 73.61
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TCCTTCTTAGCTCAGTTGGTAGAGCGCGTCACTAGTAATGACGAGGtCAGTCGTTCGAGTCGGCTAGAAGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_11.trna22 (846068-845995)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (846034-846032)	Score: 76.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCTTGGGTTCGATCCCCACGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<......>>>>.......<<<<.<<<<<<<.

Chr_11.trna23 (749506-749415)	Length: 92 bp
Type: Tyr	Anticodon: GTA at 34-36 (749473-749471)	Score: 63.98
Possible intron: 38-56 (749469-749451)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: CCGACCTTAGCTCAGTTGGAAGAGCATCAGACTGTAAtgggttacctaagcaagtcATCTGGGGGtCGCCTGTTCGAACCAGGCAGGTCGGA
Str: >>>>>>>..>>>>........<<<<.>>>>>..........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna1 (627483-627555)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (627516-627518)	Score: 59.46
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GACTGGATAGCTCAGTGGTtAGAGCATCCACCTAGTGTTGGGACGGtCCTCGGTTCAATCCCGGGTCTGGTCG
Str: >>>>>>>..>>>>........<<<<.>>>...........<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna2 (747197-747274)	Length: 78 bp
Type: Lys	Anticodon: TTT at 35-37 (747231-747233)	Score: 66.06
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: GCCCGCCTAGCTCAATCGGAtAGAGCGTCAGACTTTTAgggcATCTGAAGGcTGCGAGTTCGATCCTCGCGGTGGGCT
Str: >>>>>>>..>>>>.........<<<<.>>>>>...........<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna3 (1158874-1158955)	Length: 82 bp
Type: Val	Anticodon: CAC at 34-36 (1158907-1158909)	Score: 65.48
Possible intron: 38-46 (1158911-1158919)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GGTTCAATGGTCTAGTGGTtATGATTTCTGTCTCACActcgtggtgCACAGAAGGtCTCCAGTTCGATCCTGGATTGAACCA
Str: >>>>>>>..>>>..........<<<.>>>>>................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna4 (1223075-1223156)	Length: 82 bp
Type: Gly	Anticodon: GCC at 33-35 (1223107-1223109)	Score: 51.73
Possible intron: 37-47 (1223111-1223121)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GCATCAATGGGGTAGTGGTAACCTGGATCGTTGCCAttcgaataagcTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>..................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna5 (1251685-1251765)	Length: 81 bp
Type: Gly	Anticodon: GCC at 33-35 (1251717-1251719)	Score: 48.69
Possible intron: 37-46 (1251721-1251730)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GCATTAATGGGGTAGTGGTAACCTGGATCGTTGCCAtttgactagcTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna6 (1281413-1281502)	Length: 90 bp
Type: Tyr	Anticodon: GTA at 34-36 (1281446-1281448)	Score: 65.06
Possible intron: 38-54 (1281450-1281466)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: CCGACCTTAGCTCAGTTGGAAGAGCGCAAGACTGTAAttggaaacaccttgatcATCTTGATGtCGCCTGTTCGAGCCAGGCAGGTCGGA
Str: >>>>>>>..>>>>........<<<<.>>>>>........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna7 (1458846-1458938)	Length: 93 bp
Type: Thr	Anticodon: CGT at 33-35 (1458878-1458880)	Score: 68.28
Possible intron: 37-57 (1458882-1458902)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: GCCCTCTTAGCTCAGTGGTAGAGCGCACCACTCGTAtcgggtgttggcctgaagatcATGGTGAGGtCGGTTGTTCAATCCAGCCAGGGGGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>............................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna8 (1603091-1603174)	Length: 84 bp
Type: His	Anticodon: GTG at 34-36 (1603124-1603126)	Score: 39.78
Possible intron: 38-49 (1603128-1603139)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GTCCTTGTCGATTAGTGGTtAAATCATCTCGTTGTGGtctcggtctgctCCGAGAAGCCGGAAGTTCGAATCCTCCCTGGGACA
Str: >>>>>.>..>>>>........<<<<.>>>>>...................<<<<<....>>>.>.......<.<<<<.<<<<<.

Chr_12.trna9 (2042027-2042114)	Length: 88 bp
Type: Asp	Anticodon: GTC at 34-36 (2042060-2042062)	Score: 46.84
Possible intron: 38-53 (2042064-2042079)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *  
Seq: TCTCTGTTAGTATATCGGTtAGTACACGCGCCTGTCActgtgtttccgccggtCGCGCGAAAGCTGGGTTCGACTCCCAGACAGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna10 (2077244-2077315)	Length: 72 bp
Type: Asp	Anticodon: GTC at 34-36 (2077277-2077279)	Score: 58.70
         *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: TCTCCGTTAGTATATCGGTtAGTACACGCGCCTGTCACGCGCGAAAGCTGGGTTCGACTCCCAGACGGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna11 (1859783-1859701)	Length: 83 bp
Type: Asp	Anticodon: GTC at 34-36 (1859750-1859748)	Score: 49.25
Possible intron: 38-48 (1859746-1859736)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TCTCTGTTAGTATATCGGTtAGTACACGCGCCTGTCAgtacttctggtCGCGCGAAAGCTGGGTTCGACTCCCAGACAGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>..................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna12 (1286226-1286146)	Length: 81 bp
Type: Gly	Anticodon: GCC at 33-35 (1286194-1286192)	Score: 48.06
Possible intron: 37-46 (1286190-1286181)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GCATTAATGGGGTAGTGGTAACCTGGATCGTTGCCAttcgactagcTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna13 (1280872-1280783)	Length: 90 bp
Type: Tyr	Anticodon: GTA at 34-36 (1280839-1280837)	Score: 65.06
Possible intron: 38-54 (1280835-1280819)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    
Seq: CCGACCTTAGCTCAGTTGGAAGAGCGCAAGACTGTAAttggaaacaccttgatcATCTTGATGtCGCCTGTTCGAGCCAGGCAGGTCGGA
Str: >>>>>>>..>>>>........<<<<.>>>>>........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_12.trna14 (1254469-1254389)	Length: 81 bp
Type: Gly	Anticodon: GCC at 33-35 (1254437-1254435)	Score: 48.06
Possible intron: 37-46 (1254433-1254424)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GCATTAATGGGGTAGTGGTAACCTGGATCGTTGCCAttcgactagcTCGATCCGCCGGGGGTTCGATTCCCCCTTGATGCA
Str: >>>>>>>..>>>>.......<<<<.>>>>>.................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna1 (301013-301106)	Length: 94 bp
Type: Asp	Anticodon: GTC at 34-36 (301046-301048)	Score: 48.17
Possible intron: 38-59 (301050-301071)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: TCTCTGTTAGTATATCGGTtAGTACACGCGCCTGTCAtcatgacgtccgctatttgtgaCGCGCGAAAGCTGGGTTCGACTCCCAGACAGAGAG
Str: >>>>>>>..>>>>........<<<<.>>>>>.............................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna2 (330598-330708)	Length: 111 bp
Type: Leu	Anticodon: CAA at 35-37 (330632-330634)	Score: 55.16
Possible intron: 39-65 (330636-330662)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GGCAAGATGGCCGAGCGGTctATGGCGTGTGACTCAAGcgaaagcttgcctctgtcattaggggtTTCTCATGGGAGTATTCCCGCGTGGGTTCAAATCCCACTCTTGTCA
Str: >>>>>>>..>>>>.........<<<<.>>.>>..................................<<.<<..>>.>...<.<<..>>>>>.......<<<<<<<<<<<<.

Chr_13.trna3 (478627-478700)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (478661-478663)	Score: 77.15
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGTCTAGTTGGTcATGATTTCTGTCTAACACACAGAAGGtCCCCAGTTCGAACCTGGGTCGAACCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna4 (499396-499469)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (499430-499432)	Score: 77.15
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGTCTAGTTGGTcATGATTTCTGTCTAACACACAGAAGGtCCCCAGTTCGAACCTGGGTCGAACCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna5 (511813-511886)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (511847-511849)	Score: 77.15
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGTCTAGTTGGTcATGATTTCTGTCTAACACACAGAAGGtCCCCAGTTCGAACCTGGGTCGAACCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna6 (519130-519203)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (519164-519166)	Score: 77.15
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGTCTAGTTGGTcATGATTTCTGTCTAACACACAGAAGGtCCCCAGTTCGAACCTGGGTCGAACCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna7 (778134-778207)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (778168-778170)	Score: 75.12
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCGTCAGTTCGATCCTGGCGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna8 (808700-808784)	Length: 85 bp
Type: Gln	Anticodon: CTG at 34-36 (808733-808735)	Score: 65.64
Possible intron: 38-50 (808737-808749)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    
Seq: GGCGCTATAGTGTAGTGGTtATCACTCGGGATTCTGAtcatgcttccgatTTCCCGAAACCCAGGTTCGAACCCTGGTAGCGCCT
Str: >>>>>>>..>>>..........<<<.>>>>>....................<<<<<....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna9 (808367-808277)	Length: 91 bp
Type: Tyr	Anticodon: GTA at 34-36 (808334-808332)	Score: 63.41
Possible intron: 38-55 (808330-808313)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: CCGACCTTAGCTCAGTTGGAAGAGCGCAAGACTGTAAtcgggtgacctgaagttcATCTTGATGtCGCCTGTTCGAGCCAGGCAGGTCGGA
Str: >>>>>>>..>>>>........<<<<.>>>>>.........................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna10 (773619-773499)	Length: 121 bp
Type: Tyr	Anticodon: GTA at 34-36 (773586-773584)	Score: 60.15
Possible intron: 38-85 (773582-773535)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: CCGACCTTAGCTCAGTTGGAAGAGCGCAAGACTGTAAtcggaaaaacgtctcacggacgatcctcttgggtcgtttctgaagttcATCTTGATGtCGCCTGTTCGAGCCAGGCAGGTCGGA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......................................................<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna11 (773279-773206)	Length: 74 bp
Type: Ile	Anticodon: AAT at 35-37 (773245-773243)	Score: 75.48
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGCCGACTAGCTCAGTTGGTtAGAGCGTCGTGCTAATAACGCGAAGGtCGTCGGTTCGACCCCGGCGTTGGCCA
Str: >>>>>>>..>>>>.........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna12 (543879-543806)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (543845-543843)	Score: 77.15
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGTCTAGTTGGTcATGATTTCTGTCTAACACACAGAAGGtCCCCAGTTCGAACCTGGGTCGAACCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna13 (515271-515198)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (515237-515235)	Score: 77.15
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGTCTAGTTGGTcATGATTTCTGTCTAACACACAGAAGGtCCCCAGTTCGAACCTGGGTCGAACCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna14 (474438-474365)	Length: 74 bp
Type: Val	Anticodon: AAC at 35-37 (474404-474402)	Score: 77.15
         *    |    *    |    *    |    *    |    *    |    *    |    *    |   
Seq: GGTTCGATGGTCTAGTTGGTcATGATTTCTGTCTAACACACAGAAGGtCCCCAGTTCGAACCTGGGTCGAACCA
Str: >>>>>>>..>>>...........<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna15 (300814-300742)	Length: 73 bp
Type: Thr	Anticodon: AGT at 34-36 (300781-300779)	Score: 73.61
         *    |    *    |    *    |    *    |    *    |    *    |    *    |  
Seq: TCCTTCTTAGCTCAGTTGGTAGAGCGCGTCACTAGTAATGACGAGGtCAGTCGTTCGAGTCGGCTAGAAGGAA
Str: >>>>>>>..>>>>........<<<<.>>>>>.......<<<<<.....>>>>>.......<<<<<<<<<<<<.

Chr_13.trna16 (277355-277245)	Length: 111 bp
Type: Leu	Anticodon: CAA at 35-37 (277321-277319)	Score: 55.16
Possible intron: 39-65 (277317-277291)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |
Seq: GGCAAGATGGCCGAGCGGTctATGGCGTGTGACTCAAGcgaaagcttgcctctgtcattaggggtTTCTCATGGGAGTATTCCCGCGTGGGTTCAAATCCCACTCTTGTCA
Str: >>>>>>>..>>>>.........<<<<.>>.>>..................................<<.<<..>>.>...<.<<..>>>>>.......<<<<<<<<<<<<.

U371.trna1 (6026-5925)	Length: 102 bp
Type: Ser	Anticodon: GCT at 34-36 (5993-5991)	Score: 59.84
Possible intron: 38-57 (5989-5970)
         *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    |    *    | 
Seq: GTCACTTTGCCGGAGTGGTtAACGGGATCGCCTGCTAttggcctcagggccaggcaaAGCGGTTGGTCTTTGACCGCGAGTGTTCGAATCGCTCAGGTGACG
Str: >>>>>>>..>>>..........<<<.>>>>>...........................<<<<<.>>>>...<<<<..>>>>>.......<<<<<<<<<<<<.

