ccin_all <-read.table("dup_pair.tab",header=T,sep="\t")
genomedist<-read.table("genome_pair_config.dat",header=T,sep="\t")
# genomedist<-read.table("genome_pair_config.dat",header=F,sep="\t")
summary(genomedist)
summary(ccin_all)
ccin<- subset(ccin_all,ccin_all$ds < 2 & ccin_all$dn < 1 & ccin_all$dsdn > 0)
ccin$dnds <- 1/ ccin$dsdn

summary(ccin)
HH <- subset(ccin,ccin$geneconfig == "HeadtoHead")
HT <- subset(ccin,ccin$geneconfig == "HeadtoTail")
TT <- subset(ccin,ccin$geneconfig == "TailtoTail")
pdf("gene_pair_plots_conservative.pdf")
boxplot(HH$ds,HT$ds,TT$ds, names=c("HH","HT","TT"),main="dS")
boxplot(HH$dn,HT$dn,TT$dn, names=c("HH","HT","TT"),main="dN")
boxplot(HH$dnds,HT$dnds,TT$dnds, names=c("HH","HT","TT"),main="dN/dS")

ccin<- subset(ccin_all,ccin_all$ds < 4)
summary(ccin)
HH <- subset(ccin,ccin$geneconfig == "HeadtoHead")
HT <- subset(ccin,ccin$geneconfig == "HeadtoTail")
TT <- subset(ccin,ccin$geneconfig == "TailtoTail")
pdf("gene_pair_plots.pdf")
boxplot(HH$ds,HT$ds,TT$ds, names=c("HH","HT","TT"),main="dS")
boxplot(HH$dn,HT$dn,TT$dn, names=c("HH","HT","TT"),main="dN")
boxplot(HH$dnds,HT$dnds,TT$dnds, names=c("HH","HT","TT"),main="dN/dS")

ks.test(HH$ds,HT$ds)
ks.test(HH$ds,TT$ds)
ks.test(HH$dn,HT$dn)
ks.test(HH$dn,TT$dn)
